### ISSUE TITLE
Layer: cannot move module in new layer

### ISSUE THREAD

**Issue by stropitek** [NPellet/visualizer#1009]
To reproduce:
- Open link below
- create a blank layer
- switch to that layer
- create a module
- try to move the module

You'll not be able to move it with the error:
`Uncaught TypeError: Cannot read property 'top' of undefined`

https://www.lactame.com/visualizer/v2.74.1/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F9ad330691a8214bc023cb4542722ac84%2Fview.json

**Comment by lpatiny** [comment]
I still have some problems in my layer SVG where I have modules that can not be moved : https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F8fcf268d9a86be15206e3bc1fa1dca49%2Fview.json

**Comment by stropitek** [comment]
The bug is only fixed if the layer was created with a version of the visualizer that already has the fix (for now it's only HEAD)

**Comment by lpatiny** [comment]
You know how I can fix my view ?

**Comment by lpatiny** [comment]
OK I succeded by adding position when there where not
