### ISSUE TITLE
slick grid and search for empty field

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#1017]
I would expect that entering in the search '//' would filter for only the empty field but this does not work

**Comment by targos** [comment]
technically `//` is not a valid regexp syntax

**Comment by targos** [comment]
This is how you test for emptyness: `/^$/`

**Comment by lpatiny** [comment]
Ok thanks. Indeed '//' is an illegal regexp !

**Comment by lpatiny** [comment]
Seems /^$/ does not work in fact. Check the report in the view http://www.cheminfo.org/Spectra/Mass/Advanced_analysis/Soups_analysis_from_specific_fragments_and_peptide/index.html

**Comment by stropitek** [comment]
It works on remarks, but not on Part1

Probably because remarks is an empty string and Part1 is undefined

**Comment by lpatiny** [comment]
I think indeed in is undefined but how to deal with this. I need to find the column that are undefined in fact ...

**Comment by stropitek** [comment]
I've made a change in which all values are coerced to Strings. This means for the search engine `undefined` values are treated exactly as `"undefined"` strings. Note that because getChildSync returns `undefined` if the value is `null`, you cannot make that distinction between `null` and `undefined` values when searching

**Comment by stropitek** [comment]
Can I close this?

**Comment by lpatiny** [comment]
OK let's close it but it is not really user friendly. Maybe we will think about a better solution once ...

**Comment by targos** [comment]
Can't you coerce to an empty string in this case ?

**Comment by stropitek** [comment]
This means you have to search `undefined` by using a regexp to match an emtpy string, which is misleading IMO. I'd stick to typing `undefined` (or `undef` or `und`, strings are searched with `match`). Plus you would not be able to make the difference between empty string and `null` or `undefined`.
