### ISSUE TITLE
twig and scroll bar

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#1020]
On the view:

https://github.com/NPellet/visualizer/blob/master/src/modules/types/display/template-twig/view.js#L26

I have scroll bars that are displayed

By removing the height 100% it could solve the problem

https://github.com/NPellet/visualizer/blob/master/src/modules/types/display/template-twig/view.js#L26

But I don't know if this would be general

**Comment by targos** [comment]
usually height: 99% fixes this kind of issues

**Comment by targos** [comment]
or maybe try to use `util.getSafeElement` ? I think it was created to avoid the 99% hack

**Comment by lpatiny** [comment]
It may be due to my css. I close this ticket for the moment.
