### ISSUE TITLE
OCL rendering of big molecules ?

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#1024]
Seems in the last version my molecule for the product reference 7370 does not appear correctly. Again this bond width problem

https://eln.epfl.ch/on-tabs/

v2.75.0 is ok, v2.76.1 fails

**Comment by targos** [comment]
Probably not a bug in the visualizer

**Comment by thegodone** [comment]
Got the same issue outside the visualizer with OCL!

Envoyé de mon iPhone
