### ISSUE TITLE
In from twig the multiline of select is not supported

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#1027]
In the template of the form 'twig' module you can specify multiple select option

However if you select many lines the variable out will not contain an array but only one of the item. Would be nice to have all of them ...

```
<form>
<select size=4 multiple name='level'>
    <option value='100'>Simple</option>
    <option value='200'>Moyen</option>
    <option value='300'>Difficile</option>
</select>
</form>
```

**Comment by stropitek** [comment]
It would probably make sense for a long list so that selecting a range is easy. But for a small list I think checkboxes are much more intuitive

**Comment by lpatiny** [comment]
Yes seems indeed checkbox is really a good alternative. And will use it so this ticket is not useful for me for the moment.
It may be closed for me.
