### ISSUE TITLE
log10 as disappear from twig filter

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#1028]
Going from version 2.73 to 2.74 log10 is not available in twig. and it is also not in the twig documentation so I wonder why it ever worked !

https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2Faaf4d854d2d04c477e5bf604ac5b0934%2Fview.json&v=v2.73.0

**Comment by targos** [comment]
That's a known change. See https://github.com/NPellet/visualizer/blob/master/History.md#2740-2016-12-02

**Comment by targos** [comment]
It was made because math methods can conflict with builtin twig functions
