### ISSUE TITLE
Slick grid and query by date

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#1034]
Is it possible to search by date in slick grid ?

We have the problem on sample.cheminfo.org. I would like to search for example for all that is after first January like

![image](https://cloud.githubusercontent.com/assets/1484241/23171053/b0d69a74-f851-11e6-982e-c43423f49087.png)

But there is no result. Indeed internally it is stored as an epoch but it is not possible to let the enduser calculate the corresponding epoch. Can we do something to solve this ?

**Comment by stropitek** [comment]
Yes this could be done, but at least year+month would have to be specified, because I couldn't tell that `>2017` is a date not a number
