### ISSUE TITLE
bug in twig if template undefined

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#1039]
It may happen that we have a variable in and a template in in the twig editor. If the variable comes before the template we get:

![image](https://cloud.githubusercontent.com/assets/1484241/23751726/d7faff86-04d2-11e7-9a1f-df6c58de534b.png)

**Comment by targos** [comment]
does it block next updates?

**Comment by lpatiny** [comment]
I have some unexpected rendering problem with rendertype (qrcode) not appearing and I wonder if it could be related

**Comment by stropitek** [comment]
Just sending data before the template works fine. I would need a reproducible example, because I can't see in the module's code where that could happen.
