### ISSUE TITLE
Once there is an error we loose functionnality

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#1047]
There is an annoying bug that appeared between version v2.79.1 and v2.80.2

When we go on page:

https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F4be506f141e418c6c7226073100fe0b8%2Fview.json

And add an error in the template like `{{` for example in 2.79.1 when we remove we can again edit interactively the template while in 2.80.2 edition is gone forever ...

It seems to me that this is general in the visualizer and the sample happens with a spectra displayer. Once there is an error it will not display correct data anymore.

This will happen in the view

https://my.cheminfo.org/?v=v2.79.1&viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F9cfcc8ba7999bf41e2c88a92a96a0201%2Fview.json

**Comment by stropitek** [comment]
I'm looking into it

**Comment by stropitek** [comment]
I don't think it is related to a general problem. I fixed the bug in twig. You can create another issue for js-graph.
