### ISSUE TITLE
SOM and background color

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#1049]
It seems that we can not select as background color for a cell a jpath which is what I would need to display the some result.

https://my.cheminfo.org/?v=HEAD&viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F554613d831e22b95c6eb805bec622acb%2Fview.json

Could you add this feature ? It already exists for the points.

**Comment by targos** [comment]
a jpath based on what?

**Comment by lpatiny** [comment]
Maybe it is just that I don't understand how to represent the background color.
In the `somModel` we have an array of array of 3 points. I guess the 3 points is r g b as values between 0 and 1.
I would need somehow to convert this to a color. I tried to put a linear gradient between white and black but it fails. I guess it is also looking for minValue and maxValue to create the linear gradient so we can not use this.

So should we directly put the color in the `somModel`? This color is currently available

![image](https://cloud.githubusercontent.com/assets/1484241/25662573/48e012dc-3015-11e7-800d-fc070d540756.png)

I don't know how I'm expected to do currently to display the background and if it is possible to do.
