### ISSUE TITLE
In-place twig form edition and radio buttons

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#1054]
The values from radio button are saved correctly but not loaded in a new form (in this case a copy)

https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F3445a3018824eb277e67425eb9bb0186%2Fview.json&v=v2.81.2

**Comment by stropitek** [comment]
For me the view works as expected.

Maybe you want to uncheck the "Keep form value if data undefined" option?

**Comment by stropitek** [comment]
ahhh I think I see the problem now

**Comment by lpatiny** [comment]
I updated the example

https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F3445a3018824eb277e67425eb9bb0186%2Fview.json&v=HEAD

But now if you click on one radio button on the top, there is a value set for all the radio buttons in the bottom. I guess it is related to my exotic name ???

**Comment by stropitek** [comment]
No, it's a bug. I missed something when I did the fix.
