### ISSUE TITLE
empty array in slick grid error

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#1067]
Unhandled rejection TypeError: Cannot read property 'getChildSync' of undefined
    at W (https://www.lactame.com/visualizer/v2.85.3/modules/types/edition/slick_grid/view.js:1:18397)
    at https://www.lactame.com/visualizer/v2.85.3/modules/types/edition/slick_grid/view.js:1:19157

**Comment by stropitek** [comment]
fixed by ee072fc828d51ffd1e1a68f8aa8b084a7a4877f1
