### ISSUE TITLE
Redirect if not Chrome neither Firefox

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#1078]
In javascript you can use the following command:

var browser = navigator.userAgent.toLowerCase();
if (browser.indexOf('chrome')==-1 && browser.indexOf('firefox')==-1) {
document.write('Only Google Chrome and Firefox are currently supported');
}

< "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7"

**Comment by targos** [comment]
-1

We also support Edge. I cannot test with Safari.
If there is a specific feature that doesn't work, please say which one and we can put a warning in the modules where we need it

**Comment by lpatiny** [comment]
I should have been more precise indeed. It is the on-tabs feature that does not work and for which I would need this alert.

**Comment by targos** [comment]
It's not in this repo then 😉

**Comment by stropitek** [comment]
Moved to cheminfo/visualizer-on-tabs
