### ISSUE TITLE
Clear preferences does not work with radio buttons

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#1090]
https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F2a3b98cdae5a98b409ead16b8f4cc07f%2Fview.json

**Comment by stropitek** [comment]
@lpatiny 
Using option that says "keep form values when undefined", does it work now?

**Comment by lpatiny** [comment]
Yes it works thanks.
