### ISSUE TITLE
Drag and Drop module size

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#1093]
Since the last release the drag / drop minimal module size is much bigger and can span over the module size

https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2Feea0ba081ea2cc99da5c1aed2f29a0a8%2Fview.json

**Comment by stropitek** [comment]
You need to set the font size of the text in the preferences. I purposely removed the automatic adaptation of font size because it was not working consistently.
