### ISSUE TITLE
Unit editor and remove value

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#1101]
Currently if the unit is not specified there is an error and therefore no change.
Nevertheless we would like:
* [x] to remove everything
* [x] to put just a new number and it should keep the current unit (or base if no current unit)

**Comment by stropitek** [comment]
When removing the value, should the new value be `undefined` or `{unit: 'mm', SI: undefined}`?
I'm not sure which way to go, I see pros and cons to both

**Comment by lpatiny** [comment]
When it is a new value it is undefined so maybe remove everything should lead to the same result.
