### ISSUE TITLE
Extreme slow down if dom changes a lot with font awesome

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#1131]
There is a problem between jsgraph and fontawesome when displaying the markers.

In fact it is a side effect. It seems that font awesome watch changes in the dom and jsgraph add many elements (markers) in the dom.

@stropitek  I don't know why we are not using the old approach of pure css font-awesome. Maybe this could solve the problem ?

Here is a test case (that may take up to 1min to load)

https://www.lactame.com/visualizer/src/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/spectra_displayer/markers/view.json&dataURL=../testcase/data/spectra_displayer/markers/data.json

**Comment by stropitek** [comment]
Should be fixed by 0186ed372e471ba39786c612b66c5867c21f2260 and 5e971b9def40f04f93c1b02fa8209047cbead3a3

Note that some icons are at risk of not working anymore since we needed the js version for shimming the icon names from v4 to v5).
