### ISSUE TITLE
Slick grid problem with cell click action

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#1148]
When you mimic a cell click with an action the slick grid module correctly generates the variables out and the actions out.

However the action out does not has an undefined value.

See the example at:

http://127.0.0.1:5503/src/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/slickGridAction/view.json&dataURL=../testcase/data/slickGridAction/data.json

@stropitek Could you help to solve this issue ?

**Comment by stropitek** [comment]
Should be fixed by c5f4abe69ab3a357fe1364d8c4924ca7c12b8328
