### ISSUE TITLE
When moving quickly the previous spectrum is not always blanked

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#197]
http://npellet.github.io/visualizer/src/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/chemcalcLookup/view.json&dataURL=../testcase/data/chemcalcLookup/data.json

**Comment by lpatiny** [comment]
This bug is still present in the last version of jsgraph apparently. Any idea how to fix it ?

**Comment by NPellet** [comment]
Could very well be an issue with the slots optimization, it's the only asynchronous programming in jsGraph and I can see how this could fail. The rest I don't think so.
