### ISSUE TITLE
Global option "in situ" for variables out ?

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#228]
Need to discuss about a general way that would allow either to create a new variable out or to modify the value of an existing variable if it exists already.

Currently JSME module as a "insitu" modification and other module also allow to change the input variable.

Does it make sense that there is a checkbox in the variableOut that would allow "in situ" modification. If this checkbox is selected, a check would be done to see if this variable exists. If it exists the value would be change. If it does not exists a new variable is created.

Testcase: http://visualizer.epfl.ch/tiny/R8xsAatesHvEvUcGemrt

**Comment by andcastillo** [comment]
What was the answer to this?
