### ISSUE TITLE
View does not work in Safari

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#251]
Possibly unhandled p@http://www.lactame.com/visualizer/v2.8.3/init.js:14
@http://www.lactame.com/visualizer/v2.8.3/init.js:14
d@http://www.lactame.com/visualizer/v2.8.3/init.js:23
_callHandler@http://www.lactame.com/visualizer/v2.8.3/init.js:22
_settlePromiseFromHandler@http://www.lactame.com/visualizer/v2.8.3/init.js:22
_settlePromiseAt@http://www.lactame.com/visualizer/v2.8.3/init.js:22
_settlePromises@http://www.lactame.com/visualizer/v2.8.3/init.js:22
_consumeFunctionBuffer@http://www.lactame.com/visualizer/v2.8.3/init.js:21
consumeFunctionBuffer@http://www.lactame.com/visualizer/v2.8.3/init.js:21
@http://www.lactame.com/visualizer/v2.8.3/init.js:23
[native code]

Testcase: http://visualizer.epfl.ch/tiny/ccsgskTUNWuqakrUMPCn

**Comment by targos** [comment]
Should be fixed. You can test here: http://www.cheminfo.org/?viewURL=http%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo%2Fc8bcb5d84ca3b08bcee512fceab9823b%2Fview.json&v=head
