### ISSUE TITLE
Check the couchDB button

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#275]
There is a risk of duplicate when saving new views and not relading the page. Seems sometimes a folder is created and the view is saved in a folder with the same name.

Testcase: http://visualizer.epfl.ch/tiny/6BWuxDBxP7H9P7WsRGZ3 ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2F7d3d52c930d0c4f381df1524593b3af3%2Fview.json))

**Comment by lpatiny** [comment]
```js
            var child = last.node.findFirst(name);
```

searches in all children and for "contains"

**Comment by lpatiny** [comment]
use last.node.children and check exact equality on title
