### ISSUE TITLE
Hightlight does not work on the last right point in the chart

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#298]
When over the top right point in the chart there is no highlight. It works for all the other poirnts.

Testcase: http://visualizer.epfl.ch/tiny/ooWvIGG1iZNHBUD4boFT ([Original URL](http://www.cheminfo.org/?viewURL=http%3A%2F%2Fvisualizer.epfl.ch%2Fcheminfo%2F7d3d52c930d0c4f381df152459c1f534%2Fview.json))

**Comment by lpatiny** [comment]
Seems it still does not work. Not sure why this ticket was closed

**Comment by targos** [comment]
You told me to close it. It was a typo in the json

**Comment by lpatiny** [comment]
Oups ... sorry !
