### ISSUE TITLE
bug on module Onde with auto submit and type:array

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#303]
When i remove a line from the Onde module the data doesn't refresh

Testcase: http://visualizer.epfl.ch/tiny/6n1GIhy6uhPHf9HeBwJr ([Original URL](http://gcms.firmenich.com/visualizer/src/index.html))

**Comment by stropitek** [comment]
Fixed in 94408c9ae2893183e4fb51022a1137b1e29cea26
