### ISSUE TITLE
Drop or paste a jcamp file preferences not accessible

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#305]
Testcase: http://visualizer.epfl.ch/tiny/HUI9IQMGHYamvftXRbfh ([Original URL](http://visualizer.epfl.ch/c/home/index.html?dataURL=%2Fc%2F4a06cbbc25197036518fab2ea6ff961d%2Fdata.json&viewURL=%2Fc%2Fb50564ac9d207212f8e5ae8167cd3a72%2Fview.json))

**Comment by targos** [comment]
copy paste of old module format
