### ISSUE TITLE
loading plot export variables

### ISSUE THREAD

**Issue by andcastillo** [NPellet/visualizer#306]
The loading plot module does not allow to send variables out on an event (the triggers exist but you can't select the variable to be sent). This is important e.g. for displaying node data on mouse-over.

**Comment by lpatiny** [comment]
Testcase:
http://npellet.github.io/visualizer/src/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/loadingPlot/view.json&dataURL=../testcase/data/loadingPlot/data.json
