### ISSUE TITLE
Background color does not work in the slick grid module ?

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#308]
Testcase: http://visualizer.epfl.ch/tiny/l0AuM1SR5fVfMr8gmR6I ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2Fb50564ac9d207212f8e5ae8167cd3a72%2Fview.json))

**Comment by stropitek** [comment]
Fixed in 6dff09673838af757f4ca99dbe0c3296a44bf4e6
