### ISSUE TITLE
Plotter-Variables out

### ISSUE THREAD

**Issue by andcastillo** [NPellet/visualizer#309]
There is a recent problem to define the output variables in the plotter module. Variables out -> Mouse over a marker -> Marker infos -> jPath IS EMPTY.

http://npellet.github.io/visualizer/src/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/chart/view.json&dataURL=../testcase/data/chart/data.json

**Comment by targos** [comment]
There was a problem in this testcase indeed, because of the data.json.  
It has been fixed in 9b0919eb8ff23f6f152d7aef72e726440cdc22d3
Note that the marker information is only available for the "chart" type and it should be defined in the serie like this:
```json
{
  "x": [0,1],
  "y": [0,2],
  "info": [{"a": 1}, {"a": 2}]
}
```
