### ISSUE TITLE
Create a module that would allow to execute the code

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#310]
Would be very similar to the filter editor, allowing to get library and also having API by default

However, no variable in, no variable out, no resolve

There could be 2 mode like in the "coee editor" where you can just keep a button.

Testcase: http://visualizer.epfl.ch/tiny/PFllaC1QNEImSHlQanLG ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2F21125c3c952352c3aec9bbad0611625d%2Fview.json))

**Comment by targos** [comment]
a0043d7bf3b214c6e2c8123b8403d2b50e4e7442
