### ISSUE TITLE
Update image analysis view

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#312]
Update the view so that you can take pictures using internal camera

Testcase: http://visualizer.epfl.ch/tiny/CFkVNHNC1sAmCl5cSM3c ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2F7604efbc6cb0c45c52fa9edad8ec18a4%2Fview.json))

**Comment by stropitek** [comment]
http://www.cheminfo.org/?v=v2.10.0&viewURL=http%3A%2F%2Fvisualizer.epfl.ch%2Fcheminfo%2F7604efbc6cb0c45c52fa9edad8ec18a4%2Fview.json%3Frev%3D3-02a8c588e8c6cad6651268b6fd13d962
