### ISSUE TITLE
loading plot highlight problem

### ISSUE THREAD

**Issue by andcastillo** [NPellet/visualizer#313]
There is no highlight of the elements. 

http://npellet.github.io/visualizer/src/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/loadingPlot/view.json&dataURL=../testcase/data/loadingPlot/data.json

**Comment by targos** [comment]
was it supported before ?

**Comment by andcastillo** [comment]
Yes. In both directions.

**Comment by lpatiny** [comment]
Yes it was
