### ISSUE TITLE
Module plotter : variable out : from - to

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#314]
Could we have an output variable in the plotter module that gives the from - to current information.
I would need this to make specific calculations on the zone that is currently displayed.

Testcase: http://visualizer.epfl.ch/tiny/IM8aOkSpCnt8uQDN20wf ([Original URL](http://www.cheminfo.org/?v=HEAD&viewURL=http%3A%2F%2Fvisualizer.epfl.ch%2Fcheminfo%2Fb50564ac9d207212f8e5ae8167ed26bd%2Fview.json%3Frev%3D3-2cf46227f8d0926eee1cfd7ee5e0b0c2))

**Comment by targos** [comment]
Do you really need it as a persistent variable ?  
If it is a one time calculation, you can use an action now with the new Code executor module

**Comment by lpatiny** [comment]
OK we will use the new module. Thanks.
