### ISSUE TITLE
when rescaling plotter module, the selected (white rectangle) are not eliminated

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#323]
Testcase: http://visualizer.epfl.ch/tiny/rnG8QDarlDWxfkTT4MRc ([Original URL](file:///Users/jul/metabo/visualizer/src/index.html?dataURL=/Users/jul/metabo/lib/testcase/demoHighlightChart/data.json&viewURL=/Users/jul/metabo/lib/testcase/demoHighlightChart/view2.json))

**Comment by NPellet** [comment]
Just update to the last version of jsGraph
