### ISSUE TITLE
Type renderer of indicator in twig module

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#324]
If we have a type indicator it is displayed as a table with various background color in the cells:

http://www.cheminfo.org/?v=v2.10.0&viewURL=http%3A%2F%2Fvisualizer.epfl.ch%2Fcheminfo%2Fb50564ac9d207212f8e5ae8167bcd627%2Fview.json%3Frev%3D7-5edf8d6b049bcdf94069fdeb35921e5a

In this specific example we try to put it in a Twig template but while in the DOM the table is created, the size of the cells and background color are not ok.

Testcase: http://visualizer.epfl.ch/tiny/Le6HBXyQG4CNO6ur8u0K ([Original URL](http://visualizer.epfl.ch/c/home/index.html?v=v2.9.10&viewURL=%2Fc%2F4be506f141e418c6c7226073100fe0b8%2Fview.json))

**Comment by targos** [comment]
works in HEAD
