### ISSUE TITLE
Couch DB header button: be able to keep the order

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#325]
At the beginning we should sort in alphabetical order

Testcase: http://visualizer.epfl.ch/tiny/dDMDbPBQNSoYJS6O5jsW ([Original URL](http://visualizer.epfl.ch/c/home/index.html))

**Comment by stropitek** [comment]
@targos this is done already, right?

**Comment by targos** [comment]
I guess it is
