### ISSUE TITLE
Scatter3D - Objects disapear 

### ISSUE THREAD

**Issue by andcastillo** [NPellet/visualizer#326]
The objects disappear from the scatter 3D module as soon as they are loaded.
[Example](http://script.epfl.ch/visualizer/release/HEAD/src/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FIg4v0ZzLyC%2Ftest%40patiny.com%2FDemo%2FChart%2Fscatter3D%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FkDeDPEJmP8%2Ftest%40patiny.com%2FDemo%2FChart%2Fscatter3D%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json)

**Comment by stropitek** [comment]
Are you talking about the black squares that appear on load, and that disappear once your hover over the module with your mouse?

**Comment by andcastillo** [comment]
Yes
