### ISSUE TITLE
The view does not load anymore

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#329]
In the last version this view does not load anymore.

Don't know exactly what changed.

The error:

yntaxError: In strict mode code, functions can only be declared at top level or immediately within another function. {stack: (...), message: "In strict mode code, functions can only be declare…top level or immediately within another function."}

Testcase: http://visualizer.epfl.ch/tiny/4YR6pVPQUCiJ8eN0QoFX ([Original URL](http://visualizer.epfl.ch/c/home/index.html?v=HEAD&dataURL=%2Fc%2F4a06cbbc25197036518fab2ea6ff961d%2Fdata.json&viewURL=%2Fc%2F59dec54d14e5e206142256823e560bc2%2Fview.json))

**Comment by targos** [comment]
There is probably something wrong in a filter.
This error is thrown for scripts like this : 
```js
if (x) {
   function a() {}
}
```

the declaration of a function cannot be done in conditional blocks.
Instead you can do : 
```js
if (x) {
   var a = function() {};
}
```
Or declare the function outside of the condition.

**Comment by targos** [comment]
Is the view on cheminfo ?

I'll try to fix it

**Comment by lpatiny** [comment]
Indeed there was a function in a condition
