### ISSUE TITLE
The automatic focus in slick grid does not work alwazs

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#330]
Click on calculate
Go hover the label in the spectrum
Sometimes you see the yellow focus in the slick grid table, some times it moves but you can't see the selected line

Testcase: http://visualizer.epfl.ch/tiny/doClTFrwATo4xNFWFzPq ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2Fb50564ac9d207212f8e5ae8167cd3a72%2Fview.json&v=HEAD))

**Comment by stropitek** [comment]
Problem actually not related to slickgrid but to the core. We are testing a change that seems to work and will commit if no problems detected in other views

**Comment by stropitek** [comment]
Fixed in f36870a014682c4f6b315852dd50cfec4954a5c3
