### ISSUE TITLE
SVG editor not present

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#332]
When you try to switch to editor SVG mode there is a missing page /lib/svg-edit-2.7/svg-editor.html not found

Testcase: http://visualizer.epfl.ch/tiny/Y8dXcwN2U5XV9vogpJLL ([Original URL](http://www.cheminfo.org/index.html?flavor=1024&v=v2.10.0&dataURL=http%3A%2F%2Fvisualizer.epfl.ch%2Fcheminfo%2F59dec54d14e5e206142256823e5cf170%2Fdata.json%3Frev%3D4-db046e32fc62fff8372fa7749a7471a3&viewURL=http%3A%2F%2Fvisualizer.epfl.ch%2Fcheminfo%2F59dec54d14e5e206142256823e5cf170%2Fview.json%3Frev%3D4-db046e32fc62fff8372fa7749a7471a3))

**Comment by stropitek** [comment]
Chrome freezes with this view... Should we still support the svg editor? We'we seen that it often doesn't work with svg that were edited with illustrator or inkscape...

**Comment by lpatiny** [comment]
I would prefer to keep it because we still want to be able to edit simple graphics. But I agree that it is annoying that this view crash. Should not loose to much time on it.

**Comment by lpatiny** [comment]
There is no way to draw the SVG module anymore
