### ISSUE TITLE
Vars_out jpaths are not available unless a marker is hovered

### ISSUE THREAD

**Issue by otrobernal** [NPellet/visualizer#335]
If a plotter is created and a variable sent out is attempted, the jpaths won't be available from the module parameters menu. They become available after mouse-over a marker. Test link:
http://visualizer.epfl.ch/tiny/cjHIYmkq7tgJaJpXAlrY

**Comment by lpatiny** [comment]
Indeed the jpath for variable out is most of the time created after the first mouse out. You need to validate the preferences of the module, generate the variable out and go back in the preferences.
We don't have plan to currently improve this.
