### ISSUE TITLE
Slick grid : action out for delete / modify

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#336]
Slick grid could throw and action when deleting a line or modify a line.

the idea would be to be able to add / modify / delete data in the database and find the easiest way to achieve this. How to send only the line ? How to know the id of the deleted line ?

**Comment by thegodone** [comment]
other features related to slickgrid that can be usefull:

http://mleibman.github.io/SlickGrid/examples/example5-collapsing.html => tree view for files 

http://mleibman.github.io/SlickGrid/examples/example3b-editing-with-undo.html => undo

http://mleibman.github.io/SlickGrid/examples/example7-events.html => event to create action on line

http://mleibman.github.io/SlickGrid/examples/example-checkbox-row-select.html => multiple actions

**Comment by stropitek** [comment]
* Add "Add" and "Delete" buttons
* Custumizable buttons to send an action with the current selection
* Checkboxes for more explicit line selection

**Comment by stropitek** [comment]
The above is now all implemented.
