### ISSUE TITLE
In webservice search possibility to change form parameters

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#339]
I would like to use the webservice search in conjunction with the localstorage.

The idea is that when you go on the MSDS page, the form is filled with brand, catalog and cas number and a query is done to the server automatically.

I think the best would be to be able from the initScript to setup the values of the webservices search variable and then to trigger the query.

Would it be possible to a Variables IN that allows to change the value of the Form parameters. This would require that you can enter the name of the variable in the Form parameters.

http://visualizer.epfl.ch/cheminfo/home/index.html?config=..%2F_design%2Fflavor%2F_list%2Fconfig%2Falldocs%3Fkey%3D%22isic%22&viewURL=%2Fc%2F59dec54d14e5e206142256823eb92a7c%2Fview.json&v=v2.10.0

**Comment by targos** [comment]
if you need to fill a form with input variable, use the Onde module and connect its output to the webservice search
