### ISSUE TITLE
In the grid no way to select the column jpath

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#340]
Testcase: http://visualizer.epfl.ch/tiny/xDpEXqOydYgPHRfz8D4T ([Original URL](http://script.epfl.ch/visualizer/release/HEAD/src/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2F8D7GnNAmKv%2Ftest%40patiny.com%2FDatabases%2FAPPI%2Fimportation%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FQGdGARafvU%2Ftest%40patiny.com%2FDatabases%2FAPPI%2Fimportation%2F.results&viewBranch=Master&resultBranch=ConvertLaure&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json))

**Comment by lpatiny** [comment]
The problem is that the data contains an element named "structure" that is a reserved word.

**Comment by lpatiny** [comment]
Is this option used in some views ? Could we rename it by "_structure" ?

**Comment by stropitek** [comment]
Changed to _structure in 20f127f32645b21def744f7a08e0e13dd586b99f
