### ISSUE TITLE
If the array in the parallel coordinates has a length of 0

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#343]
In parallel coordinates, it the array in has a size of 0, the array out is not changed to have a size of 0.

Therefore in this view if there is no hit the table of result is not empty.

Testcase: http://visualizer.epfl.ch/tiny/YJ4NDZdhfhE3gAewcFNc ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2Fc8bcb5d84ca3b08bcee512fceab9823b%2Fview.json))

**Comment by targos** [comment]
Is it fixed ?
I saw this commit : ce8fa93a9a1d86121886917f1bd82657785f42d0

**Comment by lpatiny** [comment]
Fixed by #ce8fa93
