### ISSUE TITLE
Shouldn't we change the readme?

### ISSUE THREAD

**Issue by stropitek** [NPellet/visualizer#344]
The developper news are kind of outdated :stuck_out_tongue: 
We could either put the history.md in the readme.md or change the readme to be more comprehensive...

**Comment by targos** [comment]
We can use parts if this old version
https://github.com/NPellet/visualizer/blob/ad7bab942ccdfc411e3962c1b951f81a20375d10/README.md

**Comment by stropitek** [comment]
Closes with f0dcea2af6fa756239bcef19fb55537a72ac0f60
