### ISSUE TITLE
Bug in preferences

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#350]
If you click on search and then go in the configuration of the chart module, there is a bug

Uncaught SyntaxError: Failed to execute 'addColorStop' on 'CanvasGradient': The value provided ('#00.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004ff00') could not be parsed as a color.

Testcase: http://visualizer.epfl.ch/tiny/0UWvMyYrFCw1MUmPHCSV ([Original URL](http://script.epfl.ch/visualizer/release/HEAD/src/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FtT8u7TVpY8%2Ftest%40patiny.com%2FResearch%2FMass%2FSimilarity2%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FiT80d2dHUJ%2Ftest%40patiny.com%2FResearch%2FMass%2FSimilarity2%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json))

**Comment by lpatiny** [comment]
Non reproducable
