### ISSUE TITLE
Click on a peak label generates an error

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#353]
When there is an action out on click on shape it generates an error

Uncaught TypeError: data.triggerChange is not a functiondefaultmodel.js:322 dataTriggerChangeview.js:246 (anonymous function)jsgraph.js:11952 build../shapes/graph.shape.GraphShape.callHandlerjsgraph.js:11651 build../shapes/graph.shape.GraphShape._selectjsgraph.js:4814 build../graph.core.$.extend.selectShapejsgraph.js:11840 build../shapes/graph.shape.GraphShape.handlers.clickjsgraph.js:11960 build../shapes/graph.shape.GraphShape.callHandlerjsgraph.js:11882 build../shapes/graph.shape.GraphShape.handleClickjsgraph.js:11106 (anonymous function)

Testcase: http://visualizer.epfl.ch/tiny/b1xLmpdhaiO3o155k7Tb ([Original URL](http://script.epfl.ch/visualizer/release/HEAD/src/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FtT8u7TVpY8%2Ftest%40patiny.com%2FResearch%2FMass%2FSimilarity2%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FiT80d2dHUJ%2Ftest%40patiny.com%2FResearch%2FMass%2FSimilarity2%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json))

**Comment by targos** [comment]
I can't reproduce it
