### ISSUE TITLE
In the onde module, be able to select jpath in the output variable

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#361]
If we can select many jpath on the output variable we could directly apply some filter to them that would be very practical

Testcase: http://visualizer.epfl.ch/tiny/yrbYRYN01NpoH51V7MEN ([Original URL](http://visualizer.epfl.ch/c/home/index.html?dataURL=%2Fc%2F4a06cbbc25197036518fab2ea6ff961d%2Fdata.json&viewURL=%2Fc%2F4a06cbbc25197036518fab2ea6ff961d%2Fview.json))

**Comment by targos** [comment]
already supported, it was a bug in fact...
