### ISSUE TITLE
Allow the code editor to type a variable

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#363]
An option in the code editor could allow to encapsulated the value in a type

The variable out Reference could be either the original value or the typed value

Testcase: http://visualizer.epfl.ch/tiny/8s2gQnBIRf7zjfzG5IiY ([Original URL](http://visualizer.epfl.ch/c/home/index.html))

**Comment by stropitek** [comment]
Fixed in 105f24f9cfb7493fcc3ed583b77ba35156d80484
