### ISSUE TITLE
Add new renderer for markdown

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#364]
type:"markdown"

Based on the library

https://github.com/evilstreak/markdown-js

Testcase: http://visualizer.epfl.ch/tiny/xhYk7GRMtD0eRrxKgOwL ([Original URL](http://visualizer.epfl.ch/c/home/index.html))

**Comment by stropitek** [comment]
I don't think we need this since we already have a filter to convert markdown to html.

**Comment by lpatiny** [comment]
The filter is indeed enough
