### ISSUE TITLE
Edit meta data in couch DB button

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#369]
In rich text editor, the selection of the style / format fails

I receive an empty select drop down menu

Testcase: http://visualizer.epfl.ch/tiny/6RI1eiOCnoOdomlW2Uj2 ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2Fd9bd75989166b0459041ad75bb69c190%2Fview.json))

**Comment by stropitek** [comment]
Cannot reproduce...

**Comment by lpatiny** [comment]
I can

**Comment by targos** [comment]
It is a general bug with the forms component. I'll look into it

**Comment by targos** [comment]
fixed with jquery-ui update
