### ISSUE TITLE
Drag and Drop module and multiple files

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#370]
Currently the variable out contains an array of all the files that has been dropeed, even if it was done sequentially.

There could be an option that allows to reset this array each time you make a drop. Possibly it could be 2 types of variable out, the total array or the dropped array of files.

Testcase: http://visualizer.epfl.ch/tiny/Slau22tJjdrLFMkXQoQv ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2Fe35883c2ab2cc0e341e78bf33fecac84%2Fview.json))

**Comment by targos** [comment]
I think it's a bug. The module is not supposed to keep previous drops ad vitam æternam

**Comment by lpatiny** [comment]
OK then we should not add the option and fix the bug ...
