### ISSUE TITLE
CSS problem ?

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#373]
Contextual menu and "Feedback" link gives strange font

Testcase: http://visualizer.epfl.ch/tiny/762in9h4973tHCf7SLPm ([Original URL](http://direct.lactame.com/visualizer/HEAD/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2Fr9SIXzwpkK%2Ftest%40patiny.com%2FDemo%2FBasic%2FColorGrid%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2F0mQwYjPCWw%2Ftest%40patiny.com%2FDemo%2FBasic%2FColorGrid%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json))

**Comment by targos** [comment]
feedback is fixed.
I don't see any problem with the contextual menu
