### ISSUE TITLE
Autoselect view in couchdb button

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#378]
Int he couchdb save / load view there was not a button allowing to switch automatically to the visualizer version encoded in the view ?

Testcase: http://visualizer.epfl.ch/tiny/nipSVyPL7WLJL1ddUefG ([Original URL](http://visualizer.epfl.ch/c/home/index.html?dataURL=%2Fc%2F4b7669c5ec0a15e6fb3994f53b94cb4e%2Fdata.json&viewURL=%2Fc%2F0e019bb4d797395213d22aca403d2c93%2Fview.json))

**Comment by targos** [comment]
The functionality was never in the main CouchDB button. There was a special version of the button for lactame.com but it was too difficult to maintain
