### ISSUE TITLE
Show answer crash the table

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#379]
Testcase: http://visualizer.epfl.ch/tiny/wYVqQWd1hI2GA0sCvN82 ([Original URL](http://visualizer.epfl.ch/c/home/index.html?dataURL=%2Fc%2Feea0ba081ea2cc99da5c1aed2f25f8f0%2Fdata.json&viewURL=%2Fc%2Feea0ba081ea2cc99da5c1aed2f25f8f0%2Fview.json&v=HEAD))

**Comment by targos** [comment]
fixed with ce78538c47c53ac5450123c7d8eca7e3555b1cda
