### ISSUE TITLE
Table module and variable out

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#381]
In the table module, the one that has the next / previous toolbar in the bottom, the variable out can not be the full row itself.

The same is true in the "slick grid" module.

It works correctly in the slick grid module.

Testcase: http://visualizer.epfl.ch/tiny/MBWJg9J2CL5Li86fh006 ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2F802cb96adaaee45df6571be84aa4db23%2Fview.json))

**Comment by targos** [comment]
There is no problem with the module
Check the output variable name
