### ISSUE TITLE
Release v2.14

### ISSUE THREAD

**Issue by targos** [NPellet/visualizer#395]
Are we ready for it ?

**Comment by targos** [comment]
I am checking the build.

**Comment by targos** [comment]
build is OK. Anything left to fix ?

**Comment by lpatiny** [comment]
Please check my last bug report

**Comment by stropitek** [comment]
slick grid is ready

**Comment by targos** [comment]
Released and available on lactame.com: http://www.lactame.com/visualizer/v2.14.0/
