### ISSUE TITLE
In contextual menu add copy / paste data / view blank view

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#397]
The header is not always present but we would still like to be able in developer mode to copy / paste data and view.

We could therefore in the contextual menu (right click) have the options:
- copy data
- paste data
- copy view
- paste view
- blank view

This could be part of a menu called ?? Tools ? Developer ? Advanced ? ... don't know ...

Testcase: http://visualizer.epfl.ch/tiny/fxGzpgIoJV9W82u2KlcV ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2F110f4c8d040b3975bae944b6442f1d22%2Fview.json&v=v2.14.0))

**Comment by targos** [comment]
why would you not show the header in developer mode ?

**Comment by lpatiny** [comment]
Kind of "semi" developer. While there is no developer toolbar in www.cheminfo.org it is nice to be able to copy a view or copy data just to be able to check what is under the hood. The contextual menu with those options could be a way.

**Comment by stropitek** [comment]
I called the menu Utils...
