### ISSUE TITLE
View does not work with last release

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#401]
Failed to load resource: the server responded with a status of 404 (Not Found)
www.lactame.com/visualizer/latest/components/requirejs/require.js:141 Uncaught Error: Script error for: src/util/ui
http://requirejs.org/docs/errors.html#scripterror

Testcase: http://visualizer.epfl.ch/tiny/30dai3mwmOGNHApsQ1Ro ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2Fb50564ac9d207212f8e5ae8167a68433%2Fview.json))

**Comment by targos** [comment]
same as #402
