### ISSUE TITLE
Bug in preference of plotter

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#402]
Failed to load resource: the server responded with a status of 404 (Not Found)
www.lactame.com/visualizer/latest/components/requirejs/require.js:141 Uncaught Error: Script error for: jquery-ui/slider
http://requirejs.org/docs/errors.html#scripterror

Testcase: http://visualizer.epfl.ch/tiny/reo2oBQgpg5kHRs38iIk ([Original URL](http://visualizer.epfl.ch/c/home/index.html?dataURL=%2Fc%2F4a06cbbc25197036518fab2ea6ff961d%2Fdata.json&viewURL=%2Fc%2F65e411bcb10bc8b5c77cf05c6d582679%2Fview.json))

**Comment by targos** [comment]
Cannot reproduce. I guess it was a CDN cache problem.
If you encounter a "Script error" from requirejs, first try to bypass the CDN with direct=true to check if the file is really missing
