### ISSUE TITLE
Data traversing in some special cases crash

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#404]
www.lactame.com/visualizer/HEAD/src/util/datatraversing.js:297
Uncaught TypeError: Cannot read property 'value' of undefined

Testcase: http://visualizer.epfl.ch/tiny/QZlSh8CoidHOc1NlDAWx ([Original URL](http://visualizer.epfl.ch/c/home/index.html?dataURL=%2Fc%2F7d3d52c930d0c4f381df1524593b3af3%2Fdata.json&viewURL=%2Fc%2F65f84b002399eb79ec0f8bf145113d71%2Fview.json&v=HEAD))

**Comment by lpatiny** [comment]
The element is
Object {type: "regexp", value: undefined, _dataChange: undefined, __parent: DataObject, __name: "theRegexp"}
And the method
element = DataObject.check(element.get());
Will transform the element to undefined

**Comment by targos** [comment]
this is the expected behavior.
`element.get()` returns the value of element (which in this case is undefined)

**Comment by targos** [comment]
proposed fix: do not put undefined in the object. use an empty string instead
