### ISSUE TITLE
Bug because of migration of very old view

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#405]
Yocan not access preferences of the jqgrid modules

Uncaught TypeError: undefined is not a function
util.js:210

Testcase: http://visualizer.epfl.ch/tiny/FqJgNv0oVbeRmgFWhRUV ([Original URL](http://www.lactame.com/visualizer/HEAD/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FzF6X7LdYuT%2Fips%40cheminfo.org%2FStudent%2FStatistics%2FDemo%2FDemo%2FMacroFunctions%2FshowData%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FNbEb2pv5xL%2Fips%40cheminfo.org%2FStudent%2FStatistics%2FDemo%2FDemo%2FMacroFunctions%2FshowData%2F.results&viewBranch=Master&resultBranch=showRedPaints&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json))

**Comment by targos** [comment]
well the view is so old that we don't have a migrator for it. Are you asking for this ?
Maybe a better solution is to open the view in a old and compatabile version of the visualizer and try to redo it by hand on HEAD
