### ISSUE TITLE
Biojs module does not work from CDN

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#410]
Seems there is no way to draw a BioJS module when the page is on a server and the visualizer is coming from the CDN

Try for example to draw a Bio module on the page:

http://visualizer.epfl.ch/cheminfo/home/index.html?v=head

Testcase: http://visualizer.epfl.ch/tiny/pUesBVMStF3Z8NS7uysQ ([Original URL](http://visualizer.epfl.ch/c/home/index.html?v=head))

**Comment by stropitek** [comment]
Fixed with 464bf48f05545acad90eddd09578cd16db47f20b
