### ISSUE TITLE
Renderer for mathematical formula

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#412]
Using mathjax we could have a new type.

type="math"

Mathjax renders the latex syntax

This would allow to have mathematical formula in tables

**Comment by targos** [comment]
we would need to include the Mathjax library

**Comment by targos** [comment]
http://www.mathjax.org/

**Comment by targos** [comment]
We  could make many types because mathjax supports 4 types of format. Tex, Latex, MathML and ascii math.

**Comment by lpatiny** [comment]
@stropitek You could try to implement this renderer

**Comment by lpatiny** [comment]
OK Mathjax does not seem like the best approach. Let's try KaTeX:
http://www.intmath.com/blog/mathematics/katex-a-new-way-to-display-math-on-the-web-9445
Exactly what we need no ?
```
katex.render("c = \\pm\\sqrt{a^2 + b^2}", element);
```

**Comment by stropitek** [comment]
Yes perfect!

**Comment by maasencioh** [comment]
Hi, how could I use it?

**Comment by lpatiny** [comment]
As usual you can use a {type:'latex', value: ''}

However recently we implemented some new interesting feature:

- If you have a string you can force the type in a slick grid or display value module. This means a simple string can be formated as a latex mathematical formula

- Display value module has an edition option. You can then double click and edit a value while it will be displayed as a latex formula

See the example at:
https://www.lactame.com/visualizer/src/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/typerenderer/object/view.json&dataURL=../testcase/data/typerenderer/object/data.json

**Comment by maasencioh** [comment]
That's really cool feature, thanks!
