### ISSUE TITLE
Style is very different for postit

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#414]
http://www.cheminfo.org/Chemistry/2D_to_3D.html?viewURL=http%3A%2F%2Fwww.cheminfo.org%2Fcouchcheminfo%2F0e019bb4d797395213d22aca403d2c93%2Fview.json%3Frev%3D20-46b9c1f4fa2524d4b9d948f9a6ae6667&v=2.9.10

Testcase: http://visualizer.epfl.ch/tiny/MM1PtAHSCYvoxX68wp2P ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2F0e019bb4d797395213d22aca403d2c93%2Fview.json))

**Comment by targos** [comment]
@lpatiny I don't understand what it's about

**Comment by lpatiny** [comment]
This was the problem of including the visualizer in www.cheminfo.org for which the style are changed a lot in comparison with visualizer.epfl.ch

**Comment by stropitek** [comment]
I think it's about how bootstrap is changing styles. It's mostly resolved but if I have time I will create a new layout that doesn't include bootstrap. This way we will be sure that what we see on visualizer.epfl.ch is exactly what we will see on cheminfo.org

**Comment by targos** [comment]
so there is nothing we can do about it in the visualizer. I'll close it

**Comment by stropitek** [comment]
https://github.com/cheminfo/cheminfo.org/issues/29
