### ISSUE TITLE
highlight js missing ?

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#415]
Testcase: http://visualizer.epfl.ch/tiny/KNUzNKs9gTAWeyrYpdyB ([Original URL](http://visualizer.epfl.ch/c/home/index.html?v=v2.14.3&viewURL=%2Fc%2F65f84b002399eb79ec0f8bf1455bf4e3%2Fview.json))

**Comment by targos** [comment]
fixed by 1d2d61d0128cb6c0dce2d235557b2d38245be5fc
