### ISSUE TITLE
Object editor

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#417]
Change mode from contextual menu problem
Display object as text

Testcase: http://visualizer.epfl.ch/tiny/WEitlv18dEgwsMjeIuwM ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2F65f84b002399eb79ec0f8bf14583e5df%2Fview.json))

**Comment by targos** [comment]
same bug as #429
