### ISSUE TITLE
How to get syntax highlighting ?

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#420]
Testcase: http://visualizer.epfl.ch/tiny/e78j9qNTCTNJ8axihiDu ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2F65f84b002399eb79ec0f8bf1455bf4e3%2Fview.json))

**Comment by stropitek** [comment]
Use single value module instead of html editor
