### ISSUE TITLE
An error is generate with the function "set" from the code executor

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#421]
Error in getting the variable through variable.js TypeError: undefined is not a function
    at c.w.value (http://www.lactame.com/visualizer/v2.14.4/init.js:5:17734)
    at http://www.lactame.com/visualizer/v2.14.4/init.js:6:5134

Testcase: http://visualizer.epfl.ch/tiny/hqVjmMitv0jz4Dnrymc0 ([Original URL](http://visualizer.epfl.ch/c/home/index.html?v=v2.14.4&viewURL=%2Fc%2F59dec54d14e5e206142256823e8db3a3%2Fview.json))

**Comment by targos** [comment]
the error is not from the code executor but from the object editor, where you defined an output variable without a name

**Comment by lpatiny** [comment]
Salut Michael,

On a un soucis:

http://www.lactame.com/release/

A+

Luc
