### ISSUE TITLE
The drag / drop module does not work on safari ?

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#425]
http://www.cheminfo.org/?viewURL=http%3A%2F%2Fwww.cheminfo.org%2Fcouchcheminfo%2F7c676b4e77fddf06bcfdf5213b5bcd67%2Fview.json&loadversion=true&fillsearch=Maps+-+Trace+viewer

**Comment by targos** [comment]
Only Chrome implements the [DataTransferItemList](https://html.spec.whatwg.org/multipage/interaction.html#datatransferitemlist) that we use in this module

**Comment by lpatiny** [comment]
If the " DataTransferItemList" is no present and after dropping a file, change the content of the DIV to tell that this feature is not supported in your current browser and you could be interested to "upgrade" to Chrome ;)

**Comment by targos** [comment]
fixed by https://github.com/NPellet/visualizer/commit/e34832413c440f24cbe7380f8b64b35537e9adbb but only for the drop event.
You can still only CTRL+V on chrome.
