### ISSUE TITLE
Switch to layer is bugged

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#429]
I have to click 3 times in the desired layer to get it changes of layer. The other times it opens the create new layer menu.

Testcase: http://visualizer.epfl.ch/tiny/CShi0njaU1vI29VJ9Waf ([Original URL](http://www.lactame.com/visualizer/HEAD/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FbJwL4Koi2d%2Ftest%40patiny.com%2FResearch%2FNMR%2FPeakPickingService%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FEBYJNIebCr%2Ftest%40patiny.com%2FResearch%2FNMR%2FPeakPickingService%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json))

**Comment by targos** [comment]
Until this is fixed, just make sure you click on the name of the layer (the text), not anywhere in the rectangle
