### ISSUE TITLE
New type renderer for pdb and mol3d ?

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#430]
https://github.com/biasmv/pv

http://biasmv.github.io/pv/demo.html

Could you comment about the feasibility ? Would be nice in the type renderer to have options

**Comment by targos** [comment]
we have options in the type renderer

**Comment by targos** [comment]
you can specify options when the renderer is called or in the DataObject: 
```json
{
    type: 'xyz',
    value: 'blabla',
    _options: {
        opt1: true
    }
}
```

**Comment by targos** [comment]
testing in https://github.com/NPellet/visualizer/tree/bio-pv
