### ISSUE TITLE
Cannot move elements in the layer

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#432]
Once I change of layer, I could neither move nor resize any module in the view.  

Testcase: http://visualizer.epfl.ch/tiny/THmIvQGa6mJfV9Q4bHrN ([Original URL](http://www.lactame.com/visualizer/HEAD/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FbJwL4Koi2d%2Ftest%40patiny.com%2FResearch%2FNMR%2FPeakPickingService%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FEBYJNIebCr%2Ftest%40patiny.com%2FResearch%2FNMR%2FPeakPickingService%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json))

**Comment by targos** [comment]
this is a know bug. It cannot be fixed until the layer system is updated

**Comment by lpatiny** [comment]
Looking precisely to a view, this bug is related to the information about a module that is not "copied" in a specific layer.
You may check the example
http://pastebin.com/k2YQBeXv
And go on the 4th layer
The module will not move because of the line 111 and an empty definition.
In reality removing this line is enough to make the view work again.

**Comment by lpatiny** [comment]
A display: false without any other definitation can also generate this bug
```
"Admin layer": {
    "display": false
}
```

**Comment by lpatiny** [comment]
It would be nice if we can find a hack today because for complex view I'm quite annoyed

**Comment by targos** [comment]
hack is to edit the json and remove the problematic layer objects

**Comment by andcastillo** [comment]
Allow to access and modify the view.json from the view. That is a hack.

**Comment by targos** [comment]
btw I never have this issue myself. It could be nice if you explain the steps to get a bad view

**Comment by andcastillo** [comment]
I use to have those issues when save a view in different version of the visualizer.

**Comment by andcastillo** [comment]
I tried many layers, many objects and versions 2.10, 2.25 and HEAD but I could not reproduce the problem.

**Comment by andcastillo** [comment]
Well, I could do it. If you take this view: [view] (http://www.lactame.com/visualizer/HEAD/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FDYOhwnuw06%2Ftest%40patiny.com%2FDemo%2FBasic%2FtryProblem%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2Fyof4dNGOT2%2Ftest%40patiny.com%2FDemo%2FBasic%2FtryProblem%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json)

and try to add a new layer, switch to that layer, you will have the problem

**Comment by targos** [comment]
I believe this is fixed
