### ISSUE TITLE
Click on execute filter in bottom right

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#441]
When in debugger mode for a reason the API is not available in the console and it seems the context if not the correct one.

Testcase: http://visualizer.epfl.ch/tiny/Fl8W4OJAEYSsME9sqwUd ([Original URL](http://www.lactame.com/visualizer/HEAD/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FVgh2HC1FZg%2Ftest%40patiny.com%2FResearch%2FNMR%2FPeakPickingNew%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FTk0OZB692Z%2Ftest%40patiny.com%2FResearch%2FNMR%2FPeakPickingNew%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json))

**Comment by targos** [comment]
This is a bug with Chrome's developer tools.
You might want to use the Code Executor module instead
