### ISSUE TITLE
Layer selector button?

### ISSUE THREAD

**Issue by andcastillo** [NPellet/visualizer#442]
Is it possible to create a set of buttons that allows to change between layers? I just want to give more visibility to the other layers on the view.

**Comment by targos** [comment]
Yes it is possible. There are two possible ways:

## Header

If you can have a custom config, add a switchlayer element:
```json
{
        "type": "switchlayer",
        "label": "Switch layer",
        "layers": ["layer1", "layer2"]
}
```

## Button action

* Add a "client interaction" -> "button" element for each layer.
* Configure it to send the name of the layer (action text to send)
* Choose an action out name (e.g. switchLayer). It will be the same for each button
* Go to "global preferences" -> "action scripting" and create the "switchLayer" script:
`require('src/main/grid').switchToLayer(value)`

http://visualizer.epfl.ch/tiny/HdafOrmE07txn7VJI6ZO
