### ISSUE TITLE
Create a type renderer for number ?

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#444]
We often have the problem of too many decimals in a number and the requirement to format the number.
This could be in a single value module or a slick grid module for example.

One way to solve this problem is to create a second field that contains a string representation of the value that you want to display.

Does it make sense to create a type renderer for number ? If there is no option we would just immediately return the value.

Otherwise we could have different options like

using sprintf library: https://github.com/alexei/sprintf.js
using native javascript : toPrecision(), toFixed()

{type:"number", value:1234.12341234, _options: {"sprintf":"%.4f"}}
{type:"number", value:1234.12341234, _options: {"toPrecision":2}}
{type:"number", value:1234.12341234, _options: {"toFixed":1}}

**Comment by targos** [comment]
There is already a typerenderer for numbers.
I just added the easy toPrecision and toFixed options to it.

But IMO, it is easier to directly convert the number when the data is generated instead of creating complex dataobjects with options.

**Comment by lpatiny** [comment]
Would really be nice to have also the option
"sprintf":"%.4f"
Because in my slick grid I recalculate all the time the values and want to display the yield as a percentage while it is a real number currently.

**Comment by targos** [comment]
what's the difference with `toFixed: 4` ?

**Comment by lpatiny** [comment]
Indeed my mistake. I thought that with sprintf you could format a number as a percentage but it seems not to be the case.
Would be better to include "numeral" and this would solve my problem.
http://numeraljs.com/
The min version is 6.82k ... https://github.com/adamwdraper/Numeral-js/blob/master/min/numeral.min.js

**Comment by lpatiny** [comment]
we could format a number like:
{value:"1234", _options: {numeral:"0.00%"}}
And use it also in slick grid !
