### ISSUE TITLE
When adding a new module set at default title the name of the module

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#446]
For example when adding a new module Code Executor the corresponding title will be there by default.

Testcase: http://visualizer.epfl.ch/tiny/UEMmy9kf4NOYyDGlmWa0 ([Original URL](http://www.cheminfo.org/static/index.html))

**Comment by targos** [comment]
This will be done when module code is put out of "grid"

For now, I removed the "Untitled" text with 6afc765bfd363e0a5a75bf3ed97f725f11d8dd09
