### ISSUE TITLE
Text does not appear in drag / drop zone

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#451]
Testcase: http://visualizer.epfl.ch/tiny/VuOBmnOjv2UAKg3a7vum ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2F65e411bcb10bc8b5c77cf05c6d582679%2Fview.json&v=v2.15.1))

**Comment by targos** [comment]
It does...

**Comment by stropitek** [comment]
It works for me too... Before 2.15.1 there was a bug and text did not appear when no boundaries on the module. But this should be fixed now.

**Comment by lpatiny** [comment]
OK I can also not reproduce it currently.
