### ISSUE TITLE
Auto open preferenes of modules for which is is required

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#452]
Some modules like code editor or executor will not work without going to preferences.

The preferences should therefore be open automatically when drawing them if there is no alternative.

Testcase: http://visualizer.epfl.ch/tiny/nzpUeBtlOoyVetfE7Rg5 ([Original URL](http://www.cheminfo.org/static/index.html))

**Comment by targos** [comment]
It is true for almost all modules

**Comment by lpatiny** [comment]
Salut Michael,

Tu pourras m'envoyer la référence wikipedia ?

A+

Luc

**Comment by stropitek** [comment]
We've discussed this and systematically opening it is not a solution since hitting 'Cancel' will have the same effect. Instead we must find a way of saving the default module configuration in the view programmatically (without having to display the preference form and save it)

**Comment by targos** [comment]
Fixed by https://github.com/NPellet/visualizer/commit/df22ff40b7d0ec3b3ba2c1304404a77fd8855977
