### ISSUE TITLE
Add in plotter the line style

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#459]
JSGraph supports the line style

  var serie = graphinstance.newSerie( "serieTest", {}, 'line' )
    .setLabel( "My serie" )
    .autoAxis()
    .setData( seriedata )
    .setLineColor( 'olive' )
    .setLineWidth( 2 )
    .setLineStyle( 3 );

Would be nice that it is an option of the plotter so that we can superpose a large number of curves

Testcase: http://visualizer.epfl.ch/tiny/fVCxnyBYJSfRvxz5qH29 ([Original URL](http://www.lactame.com/visualizer/HEAD/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FTdWHR8sPsu%2Fips%40cheminfo.org%2FUsers%2FDiana%2Fscript%2Fdemo%2Fsimilarity-matrix%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FC7Vvyof9lH%2Fips%40cheminfo.org%2FUsers%2FDiana%2Fscript%2Fdemo%2Fsimilarity-matrix%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json))

**Comment by targos** [comment]
and what is a line style of 3 ?

**Comment by NPellet** [comment]
Affects the dashing: http://jsgraph.org/docs/serie/line/

(at the bottom)

2015-03-20 14:35 GMT+01:00 Michaël Zasso <notifications@github.com>:
