### ISSUE TITLE
Code executor : add method cancel()

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#462]
Try to add a method cancel() or something similar that would prevent execution of the variable out.

Currently when loading a page the code executor is run and the variable out are cleared even if they where defined in the global preferences as input variable with the same name.

**Comment by targos** [comment]
Create output object once at module initialization instead of every execution to keep previous values between executions.
Add methods:
* clear() : reinitialize output object
* unset(name) : delete property `name` from output object
Do not create output data if `set` is not called
