### ISSUE TITLE
plotter variable out

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#467]
I could not put out any variable when perform actions over the annotations(mouse over, click, etc).  

Testcase: http://visualizer.epfl.ch/tiny/c35IE16PEX2D0bRoKaRR ([Original URL](http://www.lactame.com/visualizer/HEAD/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2F1M24Zjmz0c%2Ftest%40patiny.com%2FResearch%2FNMR%2FAppAssingmnet%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2Fhr6EqHk41i%2Ftest%40patiny.com%2FResearch%2FNMR%2FAppAssingmnet%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json))

**Comment by targos** [comment]
closing since I am able to output variables with actions ovor annotations (called shapes in the module)
