### ISSUE TITLE
Make public

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#468]
Unknown error when trying to make public a view with the user test@patiny.com

Testcase: http://visualizer.epfl.ch/tiny/8Dsq3P8USyvW7ZAArAAk ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2F60a679a937c84f7c159dfa0f653ad13e%2Fview.json))

**Comment by stropitek** [comment]
@andcastillo 
I made your view public using the username test@patiny.com and it works...
Maybe you lost your session and were not able to save anything to the database anymore...
