### ISSUE TITLE
Cannot add slick grid on this module

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#474]
amc

Testcase: http://visualizer.epfl.ch/tiny/2HYAO5UOUiePvP6bIqzd ([Original URL](http://www.lactame.com/visualizer/HEAD/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FoYOuIc7OJT%2Ftest%40patiny.com%2FResearch%2FNMR%2FJCoupling%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FTgkjBkPmcb%2Ftest%40patiny.com%2FResearch%2FNMR%2FJCoupling%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json))

**Comment by stropitek** [comment]
Can you explain? I don't see any problem...

**Comment by andcastillo** [comment]
This is the original url: [link] (http://www.lactame.com/visualizer/HEAD/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FoYOuIc7OJT%2Ftest%40patiny.com%2FResearch%2FNMR%2FJCoupling%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FTgkjBkPmcb%2Ftest%40patiny.com%2FResearch%2FNMR%2FJCoupling%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json)
I think is a migration problem. If I change to version v2.15.0 it works, but I cant use the HEAD anymore. The original view is around 2 months old(created on the HEAD for another project), and I copied and pasted the view json from there to the current view in the HEAD version of last week.

**Comment by stropitek** [comment]
I think it works now. A major bug was introduced between last release and HEAD. Feel free to reopen if you still have problems.

**Comment by targos** [comment]
Releases are quite frequent now. You should try to develop your views on `latest` or a specific version.
