### ISSUE TITLE
3D scatter plot does not work with format chart

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#476]
Seems that the format chart is currently not supported.

Could be nice to validate the chart with

https://github.com/NPellet/visualizer/blob/gh-pages/src/lib/chart/util.js

To allow different "mistakes"

Testcase: http://visualizer.epfl.ch/tiny/PG13DBdQey44nFimHrAn ([Original URL](http://www.lactame.com/visualizer/HEAD/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FViIQGMVvIN%2Ftest%40patiny.com%2FResearch%2FBio%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FO6NthE96dB%2Ftest%40patiny.com%2FResearch%2FBio%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json))

**Comment by targos** [comment]
`lib/chart/util` has just been removed from the visualizer.

The validator is now available in `components/json-chart/dist/json-chart.min`

**Comment by stropitek** [comment]
Fixed with c9f01ac918bbaa39da45f63913f77d7272f1a0bb
