### ISSUE TITLE
too many WebGL contexts (pdb renderer)

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#484]
check if something can be done about it

**Comment by targos** [comment]
@lpatiny If you still want resolution, can you provide a view with this problem ? Otherwise this can be closed

**Comment by lpatiny** [comment]
It seems that there is no way to circumvent this limitation (it seems not to be a bug). In chrome as of today only 16 webgl context can be created.

Here is a small test case:

http://www.cheminfo.org/flavor/test/debug/Failing_webgl_too_many_context/index.html?viewURL=https%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo-public%2F45874b6300d148da891252f6260d8f04%2Fview.json%3Frev%3D2-55d3297b87e2c482cb593ad8d3bbf28d

That tries to display 20 webgl contexts.

I close this ticket because I don't see how we could solve this.
