### ISSUE TITLE
Problems migrating a view?

### ISSUE THREAD

**Issue by andcastillo** [NPellet/visualizer#486]
Chrome get stuck trying to open this view. I don't have problems with other views, so I guess it is due to a lot of migrations. It seems to be a view of version 2.3.

http://www.lactame.com/visualizer/HEAD/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FiU4YqQFBcl%2Ftest%40patiny.com%2FService%2FSpectra%2FNMR%2FpredictorCOSY%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FvbuOjPjrSc%2Ftest%40patiny.com%2FService%2FSpectra%2FNMR%2FpredictorCOSY%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json

**Comment by targos** [comment]
It is not a migration issue

There is an infinite action loop going on between your 2 spectra_displayer modules (zoom fromTo, see #489).
You can fix it temporarily by removing the action in from both modules.

**Comment by andcastillo** [comment]
mmm, then that is new. Because those views was working. What was not working is the zoom synchronisation. How can I remove the action if I cant load the view?

**Comment by lpatiny** [comment]
vi on the server and edit the view Manually ?

**Comment by targos** [comment]
v2.7.2 doesn't have the problem:
http://www.lactame.com/visualizer/v2.7.2/?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FiU4YqQFBcl%2Ftest%40patiny.com%2FService%2FSpectra%2FNMR%2FpredictorCOSY%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FvbuOjPjrSc%2Ftest%40patiny.com%2FService%2FSpectra%2FNMR%2FpredictorCOSY%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json
