### ISSUE TITLE
Share view should save the version of the visualizer

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#488]
Currently when using the "Share view" button in the header, the link points to the "latest" version of the visualizer. This could lead to some compatibility problem on the long term.

Would be better that it points to the version in which the view was saved.

**Comment by targos** [comment]
If you share your view while on HEAD then it is normal.
I just checked from a release and it works correctly: http://visualizer.epfl.ch/tiny/N8hUqQa1axA06qomN8ko

**Comment by lpatiny** [comment]
Sorry my mistake !
