### ISSUE TITLE
Strange behaviour ... To discuss with  Daniel

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#491]
Look like there is a conflict between the twig table and the result obtained in the filter ... I don't unsersant

Testcase: http://visualizer.epfl.ch/tiny/F4zGvCNDBbglElU0nTic ([Original URL](http://www.lactame.com/visualizer/HEAD/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FO2wSmUZGrq%2Ftest%40patiny.com%2FResearch%2FBio%2FTable2Blast%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FUysSSe8dNR%2Ftest%40patiny.com%2FResearch%2FBio%2FTable2Blast%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json))

**Comment by lpatiny** [comment]
Seems related to my session ... forget it
