### ISSUE TITLE
View migratioin problem, all the modules are doubled !!!!

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#499]
Try to migrate this view to 2.17.0 ... all the modules will be there twice.

Testcase: http://visualizer.epfl.ch/tiny/PYn03K2gDEOumK8vQWyr ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2F65e411bcb10bc8b5c77cf05c6d582679%2Fview.json&v=v2.16.0))

**Comment by targos** [comment]
What about latest ?
2.17.0 has a bug and doesn't work on Safari

**Comment by lpatiny** [comment]
No even in the head in failed

http://www.lactame.com/visualizer/head/index.html?viewURL=http://visualizer.epfl.ch/x/PYn03K2gDEOumK8vQWyr/view.json&dataURL=http://visualizer.epfl.ch/x/PYn03K2gDEOumK8vQWyr/data.json

Interestingly in the console we have 12 times the message:

Could not remove module from dom. The module has not been loaded yet
/visualizer/head/src/main/entrypoint.js:187 No module urls rewritten in the view

**Comment by targos** [comment]
I see one line with `Module urls were rewritten...`
Investigating

**Comment by targos** [comment]
The problem is in Grid and will probably disappear with #475

In the mean time, you can just save the view and reload.
The modules appear twice but only in the UI, not in the view.json

**Comment by targos** [comment]
hacky fix in 8955bd02b055f6f074d977e0799aa4818419be7a
