### ISSUE TITLE
The text in the bottom of the view is not HTML formatted

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#500]
In version v2.16.0 It was HTML formatted text but here we see HTML code. However if we open it we really see the editor with HTMLK text.

Testcase: http://visualizer.epfl.ch/tiny/6RlxHcfWT8eY4xFCYjuG ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2Feea0ba081ea2cc99da5c1aed2f29a0a8%2Fview.json&v=v2.17.2))

**Comment by targos** [comment]
my bad, I didn't check the default value when I worked on the new typerenderer.
It is fixed now
