### ISSUE TITLE
Migration of the view fails

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#501]
NMR containing 2D spectra seems to fail during migration. Not obvious why

http://visualizer.epfl.ch/c/home/index.html?v=v2.16.0&dataURL=%2Fc%2F59dec54d14e5e206142256823e5cf170%2Fdata.json&viewURL=%2Fc%2F59dec54d14e5e206142256823e568a49%2Fview.json

**Comment by targos** [comment]
Migration doesn't fail.
Like in #486 you have a zoom action out that is the same of the action in of your spectra displayer.
Previously it was silently not working and now there is an infinite action loop...

**Comment by targos** [comment]
closing as duplicate
