### ISSUE TITLE
Parallel coordinates module have scroll bars

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#504]
Testcase: http://visualizer.epfl.ch/tiny/MyM3iqSSgtvXYLAGjGTA ([Original URL](http://visualizer.epfl.ch/c/home/index.html?v=v2.17.2&dataURL=%2Fc%2F59dec54d14e5e206142256823e5bb2fd%2Fdata.json&viewURL=%2Fc%2Fcb8a3f4de3c6eef86332f89ed5fa9b80%2Fview.json))

**Comment by targos** [comment]
fixed in dbcdd925673df5b8fa6537c6892bef28402d2d6f and 731e9690e6a87bbff353eff062aed86a15d02dd3
