### ISSUE TITLE
Renderer of color is not triggered

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#509]
Check in this view the second line. If you resize the single value module the color appears

Testcase: http://visualizer.epfl.ch/tiny/4Uf0qGTUoPcbJpPMNfKh ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2F92a706528b15c5663cb5844af07a6619%2Fview.json))

**Comment by targos** [comment]
I reopen beacuse we shouldn't need this hack
