### ISSUE TITLE
Fullscreen problem

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#510]
The fullscreen only use the lower half part of the screen to display the module content.

Testcase: http://visualizer.epfl.ch/tiny/eth2FVc1m9MbKCBCs88O ([Original URL](http://visualizer.epfl.ch/c/home/index.html?v=v2.17.5&viewURL=%2Fc%2Feea0ba081ea2cc99da5c1aed2f29a0a8%2Fview.json))

**Comment by targos** [comment]
I cannot reproduce this. It uses my entire screen.
Do you have the problem with a specific module ? I tried with spectra displayer and jsme

**Comment by andcastillo** [comment]
All the modules. Chrome Version 42.0.2311.90 (64-bit), OS: Yosemite 10.90. The problems appears on version 2.16.0 of the visualizer, only for Safari and Chrome. Mozilla works ok, internet explorer is dead.

**Comment by targos** [comment]
Confirmed on Chrome 42. It works on next version (43) though.
It was also working correctly before (we didn't change anything related to the full screen recently)

**Comment by targos** [comment]
It may be a bug in chromium... I will try to create an issue in their bug tracker

**Comment by andcastillo** [comment]
But Safari is having the same issue. And remember is only since version 2.16 of the visualizer.

**Comment by targos** [comment]
It was introduced with [this commit](5ea4765b28da5ba754c4bab387df5c6a8e16611c)
I will let @stropitek decide what to do.
But still, it works on next Chrome so it may be a bug with the fullscreen mode
