### ISSUE TITLE
In code executor add an option to "execute on load"

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#512]
Testcase: http://visualizer.epfl.ch/tiny/VeHfEwsBPCFE9kyYYWQn ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2F92a706528b15c5663cb5844af07d2815%2Fview.json))

**Comment by targos** [comment]
This would be a new event ?

**Comment by lpatiny** [comment]
Would be a checkbox in the options if we want to keep the compatibility
But indeed it would be a new type of event so that we can filter it out as well
