### ISSUE TITLE
Object editor:displays [object object] instead of object properties

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#513]
Testcase: http://visualizer.epfl.ch/tiny/mYRmVYVdW5sPxKbbbs92 ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2F92a706528b15c5663cb5844af09964b9%2Fview.json))

**Comment by stropitek** [comment]
(use the orignal url...)

**Comment by stropitek** [comment]
Seems to have something to do with executing the code in a sandbox
Same code in code executor and filter editor does not give the same result in object editor
http://visualizer.epfl.ch/tiny/bA9uYEpUkkm23W6BPhWY
