### ISSUE TITLE
Bug in sparkline renderer ??

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#514]
There could be a but in the sparkline renderer if type=discrete

Strange because type="bar" works correctly

Testcase: http://visualizer.epfl.ch/tiny/NZorTzRgWBMlaJff6V3L ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2F92a706528b15c5663cb5844af07d2815%2Fview.json))

**Comment by targos** [comment]
@stropitek do you have any idea ?

**Comment by stropitek** [comment]
The option width: '100%' is not supported by sparkline 'discrete' type whereas the 'line' type for example supports it... You have to put a number or to use 'auto'.
The typerenderer uses '100%' as the default width option.
We have two solutions:
 * keep as is and discrete will not work unless we override the width option in _option
 * remove the default option to 100% in the typerenderer, and we will have to specify 100% to make it look nicer in compatible types.

**Comment by lpatiny** [comment]
Third option, check if it is of 'discrete' type or a type that does not support 100% and then switch to 'auto' ?
