### ISSUE TITLE
Bug in Safari ;)

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#517]
Execute doesn't work on Safari

Testcase: http://visualizer.epfl.ch/tiny/ANMcsuZInSX8iKLmXWVk ([Original URL](http://www.cheminfo.org/static/index.html?viewURL=http%3A%2F%2Fwww.cheminfo.org%2Fclp%2Fc%2Fa27d59b20df929892c57461a03195941%2Fview.json))

**Comment by targos** [comment]
solution : `win.parent = null` in sandbox

**Comment by targos** [comment]
fixed in e6b0c8ee0b1ef700a6bd1c4d7b709164fef51478 and d7b9807e48d34454b50bb1dfaac7e27e858bb1a7
