### ISSUE TITLE
Type renderer problems

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#518]
Some renderers do not work as intended (Chromium Version 37.0.2062.120 Built on Ubuntu 12.04, running on LinuxMint 13 (281580)).

- regexp renderer: [0-9]{2,3}|ABC produces something like "ABC" "9" on a gray background
- 3D chemical renderers: blank output.

Alain Borel

Testcase: http://visualizer.epfl.ch/tiny/LoauKjvBGHjHVisXWqpH ([Original URL](http://www.cheminfo.org/static/index.html?viewURL=http%3A%2F%2Fwww.cheminfo.org%2Fclp%2Fc%2Fa27d59b20df929892c57461a03305256%2Fview.json%3Frev%3D1-6d48a5e61f1cd3c6f5db7a17e87018f3))

**Comment by targos** [comment]
We cannot support all versions of Chrome, the release cycle is too fast (current v42 doesn't have this problem)
