### ISSUE TITLE
slickgrid - cell navigation should be activate with isEditable

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#526]
Remove the cell Navigation options

Testcase: http://visualizer.epfl.ch/tiny/592aCt7iJDL43Gegv62u ([Original URL](http://www.lactame.com/visualizer/v2.17.6/index.html?viewURL=http://visualizer.epfl.ch/x/xjzwgl0UvQk5UjayFig8/view.json&dataURL=http://visualizer.epfl.ch/x/xjzwgl0UvQk5UjayFig8/data.json))

**Comment by lpatiny** [comment]
Duplicate #525
