### ISSUE TITLE
Spectrum displayer

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#531]
Spectrum displayer fails to plot 1D XY Array. 

Testcase: http://visualizer.epfl.ch/tiny/0N2hm5aU4JNXNzjYT6no ([Original URL](http://www.lactame.com/visualizer/HEAD/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2Fr7cVWhp7lb%2Ftest%40patiny.com%2FResearch%2Fcoffee%2FtestBug%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2F3cvdSHsHFQ%2Ftest%40patiny.com%2FResearch%2Fcoffee%2FtestBug%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json))

**Comment by lpatiny** [comment]
The specification may not be clear but it should be a 1D XY array and not an 1D array of array
Meaning
[x1,y1,x2,y2,x3,y3,...]

Should do a code like:

for(var i=0;i<nbPoints;i++){
    spec[i*2]=i/100;
    spec[i*2+1]=i;
    x[i]=i/100;
    y[i]=i;
}
