### ISSUE TITLE
Progress bar and expected remaining time

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#536]
Try to evaluate the remaining time for the calculation and give the possibility to display it in the progress bar.

**Comment by targos** [comment]
I can add an input variable for custom text

**Comment by lpatiny** [comment]
I think the module could evaluate itself the remaining time bar and just display it has hh:mm:ss

**Comment by targos** [comment]
then we need to add the concept of "start"

**Comment by targos** [comment]
and 0 as input would restart the timer

**Comment by targos** [comment]
Has been implemented a while ago
