### ISSUE TITLE
The 3D function does not appear when clicked on a line

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#542]
Testcase: http://visualizer.epfl.ch/tiny/nKGBBphK47fXZMBGh0rn ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2F65f84b002399eb79ec0f8bf145483610%2Fview.json))

**Comment by targos** [comment]
the update handler is not implemented https://github.com/NPellet/visualizer/blob/gh-pages/src/modules/types/chart/advanced/plot_function/view.js#L148-L151
