### ISSUE TITLE
Scroll bar are present in twig editor and post-it module

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#547]
In the last release some scroll bars have appeared

Testcase: http://visualizer.epfl.ch/tiny/BO6APAJsMLz47znwckJZ ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2Fd3c3001cb6f7868c571bdc165c88a649%2Fview.json))

**Comment by stropitek** [comment]
It's not the release. You've set styles in the template with a margin which is causing the problem. You should use padding instead.

**Comment by lpatiny** [comment]
But for the posit we don’t specify styles ?

**Comment by lpatiny** [comment]
OK for the post-it if you let the frame option (even if there are none displayed) it works correctly.
