### ISSUE TITLE
New module: hexagonal chart

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#550]
Create a new module allowing to create an hexagonal chart

format:
{
type:"chart",
value: {
axis:["N","S","O"],
data:[[0,0,0],[1,1,0],[0,1,1]],
info:[{color:'red', label:'C'},{color:'blue'},{color:'green'}]
}}

options in module:
* color jpath (from info)
* size (default 6)
* label color
* label size ... ? Use the css selector ?

How to display the color scale ?

![ac-2013-00418j_0003](https://cloud.githubusercontent.com/assets/1484241/7583670/bea57ad2-f897-11e4-9b95-b4af2b4caf77.gif)

**Comment by targos** [comment]
can we close this or there are still some features to implement ?

**Comment by targos** [comment]
ping @stropitek

**Comment by stropitek** [comment]
Let's not close it for now. I realize that I was using the chart format wrongly.

Would it make sense to allow one label per point in the chart format? For now labels are only for a serie.

```json
{
  "type": "chart",
  "value": {
    "data": [{
      "x": [1,2],
      "y": [3,2],
      "labels": ["point1", "point2"],
      "label": "Serie 1"
}]
}
}
```

**Comment by targos** [comment]
I would put it in the info array:
`... info: [{label: 'point1'}, {label: 'point2'}] ...`
and mention in the inexisting doc of the module that it should be here :smile:
