### ISSUE TITLE
Problem on Safari and included visualizer in an iframe

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#552]
When going on page 

http://cheminfo.epfl.ch

From safari there is an exception.

SecurityError: DOM Exception 18: An attempt was made to break through the security policy of the user agent.

                        var c = window.openDatabase("__sysdb__", 1, "System Database", b);
                        c.transaction(function(b) {
                            b.executeSql("SELECT * FROM dbVersions", [], function() {}, function() {

**Comment by targos** [comment]
could you try with a real iframe ? `<frameset>` is deprecated

**Comment by targos** [comment]
@lpatiny what is the status on this one ?
