### ISSUE TITLE
papaparse

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#563]
Why this is wrong from the console ?

require(["www.lactame.com/visualizer/head/components/papa-parse/papaparse"], function(AB) {console.log(AB)})

Testcase: http://visualizer.epfl.ch/tiny/NmzsKQt1cfzo9dMF8rf3 ([Original URL](http://www.cheminfo.org/static/index.html?viewURL=http%3A%2F%2Fwww.cheminfo.org%2Fclp%2Fc%2Fa27d59b20df929892c57461a030db2e5%2Fview.json))

**Comment by targos** [comment]
only the minified version is included in the build: components/papa-parse/papaparse.min

**Comment by lpatiny** [comment]
The same is true on the head or with minified

**Comment by targos** [comment]
on the head as well because the library is not AMD so only the minified version is being shimmed: https://github.com/NPellet/visualizer/blob/gh-pages/src/init.js#L85-L87

**Comment by stropitek** [comment]
Apparently will also not work with the full url for those non AMD libraries
Only works with components/papa-parse/papaparse.min

**Comment by lpatiny** [comment]
OK thanks. The conclusion is that indeed you need to always use the minified version otherwise it is not AMD.
But why in the init.js you need to export Papa ?
https://github.com/NPellet/visualizer/blob/gh-pages/src/init.js#L85-L87

**Comment by targos** [comment]
it is not exported. this line tells requirejs what is the name of the global variable
