### ISSUE TITLE
lighten and organize the repository

### ISSUE THREAD

**Issue by targos** [NPellet/visualizer#567]
## remove components from the git tree
* __134,7 MB less !__
* then need to manually install them, but it's just an NPM command...

## move to master branch
* we don't need gh-pages anymore thanks to lactame.com
* we could then use gh-pages to host a website about the project / the docs

## TODO
* preparation has to be done on the build servers before we proceed

**Comment by targos** [comment]
Everything is ready !

@NPellet could you please switch the default branch to master in https://github.com/npellet/visualizer/settings ?

**Comment by NPellet** [comment]
done
