### ISSUE TITLE
In couchDB button, Edit meta does not allow html editor

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#571]
There is one error

Uncaught TypeError: Cannot read property 'icons' of null(anonymous function) @ ckeditor.js:214(anonymous function) @ ckeditor.js:214CKEDITOR.scriptLoader.load.k @ ckeditor.js:209CKEDITOR.scriptLoader.load @ ckeditor.js:209CKEDITOR.resourceManager.load @ ckeditor.js:213j @ ckeditor.js:214(anonymous function) @ ckeditor.js:215k @ ckeditor.js:225(anonymous function) @ ckeditor.js:224(anonymous function) @ ckeditor.js:422(anonymous function) @ ckeditor.js:214CKEDITOR.scriptLoader.load.k @ ckeditor.js:209CKEDITOR.scriptLoader.load @ ckeditor.js:209CKEDITOR.resourceManager.load @ ckeditor.js:213CKEDITOR.tools.extend.getStylesSet @ ckeditor.js:422i @ ckeditor.js:224(anonymous function) @ ckeditor.js:224e @ ckeditor.js:208CKEDITOR.lang.load @ ckeditor.js:208h @ ckeditor.js:223(anonymous function) @ ckeditor.js:223b @ ckeditor.js:432CKEDITOR.skin.loadPart @ ckeditor.js:434f @ ckeditor.js:223(anonymous function) @ ckeditor.js:223h @ ckeditor.js:10CKEDITOR.event.CKEDITOR.event.fire @ ckeditor.js:11CKEDITOR.editor.CKEDITOR.editor.fire @ ckeditor.js:13CKEDITOR.event.CKEDITOR.event.fireOnce @ ckeditor.js:12CKEDITOR.editor.CKEDITOR.editor.fireOnce @ ckeditor.js:13d @ ckeditor.js:221j @ ckeditor.js:223(anonymous function) @ ckeditor.js:220(anonymous function) @ ckeditor.js:23setTimeout (async)CKEDITOR.tools.setTimeout @ ckeditor.js:23a @ ckeditor.js:220a @ ckeditor.js:294CKEDITOR.replace @ ckeditor.js:298e.inDom @ element.js:1(anonymous function) @ init.js:25a.extend.eachFieldElements @ init.js:25(anonymous function) @ init.js:25b.extend.eachFields @ init.js:25a.extend.inDom @ init.js:25(anonymous function) @ init.js:25(anonymous function) @ init.js:25b.extend.eachGroupElements @ init.js:25(anonymous function) @ init.js:25a.extend.eachGroups @ init.js:25b.extend.eachElements @ init.js:25b.extend.inDom @ init.js:25(anonymous function) @ init.js:25(anonymous function) @ init.js:25b.extend.eachSectionElements @ init.js:25(anonymous function) @ init.js:25a.extend.eachSections @ init.js:25b.extend.eachElements @ init.js:25b.extend.inDom @ init.js:25(anonymous function) @ init.js:26a.extend.eachSectionElements @ init.js:26a.extend.inDom @ init.js:26(anonymous function) @ couchdb2.js:1k @ init.js:2l.fireWith @ init.js:2e.(anonymous function) @ init.js:2(anonymous function) @ init.js:26(anonymous function) @ init.js:2k @ init.js:2l.fireWith @ init.js:2(anonymous function) @ init.js:2k @ init.js:2l.fireWith @ init.js:2e.(anonymous function) @ init.js:2(anonymous function) @ init.js:25(anonymous function) @ init.js:2k @ init.js:2l.add @ init.js:2(anonymous function) @ init.js:2_.extend.each @ init.js:1(anonymous function) @ init.js:2_.extend.Deferred @ init.js:2d.then @ init.js:2(anonymous function) @ init.js:25context.execCb @ require.js:1665Module.check @ require.js:874Module.enable @ require.js:1158Module.init @ require.js:782(anonymous function) @ require.js:1431setTimeout (async)(anonymous function) @ require.js:1770localRequire @ require.js:1420b.extend.makeElement @ init.js:25a.extend.getFieldElement @ init.js:25a.extend.fillElement @ init.js:25a.extend._fill @ init.js:25a.extend.fill @ init.js:25b.extend._fill @ init.js:25b.extend._fillGroups @ init.js:25b.extend.fill @ init.js:25b.extend._fill @ init.js:25b.extend._fillSections @ init.js:25b.extend.fill @ init.js:25b.extend._fill @ init.js:25b.extend._fillSections @ init.js:25a.extend.fill @ init.js:26(anonymous function) @ couchdb2.js:1c @ init.js:40b._settlePromiseFromHandler @ init.js:39b._settlePromiseAt @ init.js:39b._settlePromiseAtPostResolution @ init.js:39c._drainQueue @ init.js:38c._drainQueues @ init.js:38drainQueues @ init.js:38Mutation (async)(anonymous function) @ init.js:39c._queueTick @ init.js:38e @ init.js:38j.hasDevTools.c.invoke @ init.js:38b._then @ init.js:39b.then @ init.js:39(anonymous function) @ couchdb2.js:1k @ init.js:2l.fireWith @ init.js:2e.(anonymous function) @ init.js:2(anonymous function) @ init.js:26(anonymous function) @ init.js:2k @ init.js:2l.fireWith @ init.js:2(anonymous function) @ init.js:2k @ init.js:2l.fireWith @ init.js:2e.(anonymous function) @ init.js:2(anonymous function) @ init.js:25context.execCb @ require.js:1665Module.check @ require.js:874Module.enable @ require.js:1158Module.init @ require.js:782(anonymous function) @ require.js:1431setTimeout (async)(anonymous function) @ require.js:1770localRequire @ require.js:1420b.extend.addField @ init.js:25b.extend.setStructure @ init.js:25a.extend._addElement @ init.js:25a.extend._addElements @ init.js:25a.extend._addGroups @ init.js:25a.extend.setStructure @ init.js:25a.extend._addElement @ init.js:25a.extend._addElements @ init.js:25a.extend._addSections @ init.js:25a.extend.setStructure @ init.js:25a.extend._addElement @ init.js:25a.extend._addElements @ init.js:25a.extend._addSections @ init.js:25a.extend.setStructure @ init.js:26f.inherits.metaData @ couchdb2.js:1f.append.a.append.append.e.color @ couchdb2.js:1f.doClick @ init.js:9(anonymous function) @ init.js:9_.event.dispatch @ init.js:2q.handle @ init.js:2

**Comment by stropitek** [comment]
Fixed in f0ff9f952b2912ebc9c4bf637bd0b9c72f253325
