### ISSUE TITLE
word count and changing preferences

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#574]
Changing preferences does not repaint the module.

Testcase: http://visualizer.epfl.ch/tiny/XrZrBvQtEgdVTBI9u6KH ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2F554613d831e22b95c6eb805bec1437a2%2Fview.json&v=HEAD))

**Comment by lpatiny** [comment]
@David-Turbert
