### ISSUE TITLE
expose switchLayer in API

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#578]
require('src/main/grid').switchToLayer(value)

**Comment by stropitek** [comment]
We cannot do that (easily) because we would have circular dependency. api requires grid and grid requires api. Requirejs does not accept that.

**Comment by targos** [comment]
If something from API is required by core, we should extract it in another file

**Comment by NPellet** [comment]
You can do that by using require, not define...

2015-05-26 11:16 GMT+02:00 Michaël Zasso <notifications@github.com>:
