### ISSUE TITLE
In code executor the result is [object Object]

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#582]
In code executor we obtain as result [object Object] instaed of <a>1</a>

Testcase: http://visualizer.epfl.ch/tiny/eAFgze9WqMwK4XpT7Jp6 ([Original URL](http://www.cheminfo.org/static/index.html?viewURL=http%3A%2F%2Fwww.cheminfo.org%2Fclp%2Fc%2Fa27d59b20df929892c57461a034ed281%2Fview.json))

**Comment by targos** [comment]
This is again a problem related to the sandbox...
We have 2 options :
* Stop using the sandbox
* Load dependencies in the sandbox instead of passing them from the global window
