### ISSUE TITLE
JSME module and action out

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#598]
We would need to have action out for various events but lets start with the more important, clickAtom.

We would like thanks to a code executor to know on which atom we are clicking. This will allow to add in a slick grid table the corresponding atom number.

**Comment by stropitek** [comment]
When click/hover an atom you will get
```json
{"atom": 2}
```

When click/hover a bond you will get
```json
{"bond": 2}
```

Hovering out will also generate an action, but the value of the bond/atom will be 0.
```json
{"atom": 0}
```
```json
{"bond": 0}
```
