### ISSUE TITLE
how to use numeric.js directly in the visualizer ?

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#601]
I have the impression that numeric.js is not compatible with require ? Is this the case ?

**Comment by thegodone** [comment]
It works in nodejs and we also need it code executor

Envoyé de mon iPhone

**Comment by targos** [comment]
If a library is available on NPM (and numeric is), you can always try the browserify CDN : https://wzrd.in/standalone/numeric. Most of the time it works

**Comment by lpatiny** [comment]
A
[testcase](http://www.cheminfo.org/Tutorial/9.%20Advanced/9.13_Numeric.js.html?viewURL=http%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo%2F16e029673e68d05b6df709e29778daed%2Fview.json%3Frev%3D1-9947be782cf907d6602882bb362a79a8&v=v2.22.1) has been created.

Seems to work

**Comment by targos** [comment]
Shouldn't we advertise the use of ml packages instead? numeric is good but it is not maintained and I'd like to have some feedback on the matrix library.

**Comment by thegodone** [comment]
Bonjour NPellet/visualizer,
guillaume godin vous a laissé un message sur IQ Elite 
Cliquez ici a.iqelite.com/j/2vBDJ3/of3/?hg=QXPcWmK0Zz pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=44b7d1e2&email=reply@reply.github.com.&hg=QXPcWmK0Zz
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------
