### ISSUE TITLE
Three generates plenty of warning

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#606]
Just click on the view and get the "Demo TSV"

THREE.PlaneGeometry: Consider using THREE.PlaneBufferGeometry for lower memory footprint.
4three.min.js:746 THREE.PlaneGeometry: Consider using THREE.PlaneBufferGeometry for lower memory footprint.
4three.min.js:746 THREE.PlaneGeometry: Consider using THREE.PlaneBufferGeometry for lower memory footprint.
three.min.js:746 THREE.PlaneGeometry: Consider using THREE.PlaneBufferGeometry for lower memory footprint.
three.min.js:746 THREE.PlaneGeometry: Consider using THREE.PlaneBufferGeometry for lower memory footprint.
three.min.js:746 THREE.PlaneGeometry: Consider using THREE.PlaneBufferGeometry for lower memory footprint.
17three.min.js:2 THREE.WebGLRenderer: Texture is not power of two. Texture.minFilter should be set to THREE.NearestFilter or THREE.LinearFilter. (  )

Testcase: http://visualizer.epfl.ch/tiny/UJ6HTOTV5UF8zYy2kI9V ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2Ff370dff5637668c2259a3124839b3ebd%2Fview.json))

**Comment by stropitek** [comment]
Fixed
