### ISSUE TITLE
Strange error when using this view on the head

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#612]
Error while updating module :  Cannot assign to read only property 'molfile' of CC
JME 2015-06-25 Sat Jun 27 17:39:53 GMT+200 2015
 
  2  1  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.7000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2124    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
M  END
 TypeError: Cannot assign to read only property 'molfile' of CC
JME 2015-06-25 Sat Jun 27 17:39:53 GMT+200 2015
 
  2  1  0  0  0  0  0  0  0  0999 V2000
    0.0000    0.7000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
    1.2124    0.0000    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
M  END

    at Model.setData (http://www.lactame.com/visualizer/HEAD/modules/default/defaultmodel.js:261:34)
    at http://www.lactame.com/visualizer/HEAD/modules/default/defaultmodel.js:181:42

Testcase: http://visualizer.epfl.ch/tiny/qjuHy7KB53iYhrve6Etd ([Original URL](http://visualizer.epfl.ch/c/home/index.html?v=HEAD&viewURL=%2Fc%2F4361c134eb36eff59b0388449f0bf0de%2Fview.json))

**Comment by stropitek** [comment]
I don't know exactly why but you shouldn't have a reference in the controller which name is 'value'. Seems that the visualizer gets confused about this.
