### ISSUE TITLE
FYI: Breaking change in jsGraph

### ISSUE THREAD

**Issue by NPellet** [NPellet/visualizer#614]
in jsGraph 1.11.3-11, ```graph.newSerie( name )```, name has now to be unique. If the serie already exists, jsGraph will return the currently existing serie.

You should check your code that nothing will break before you upgrade the library

**Comment by targos** [comment]
Unique inside the same graph, right ?
Can two different instances use the same name ?

**Comment by NPellet** [comment]
Yes of course they can.

2015-06-30 17:47 GMT+08:00 Michaël Zasso <notifications@github.com>:

**Comment by NPellet** [comment]
But in 1.12, there will be more breaking changes.
I'm working on a partial rewrite.

2015-06-30 17:55 GMT+08:00 Norman Pellet <norman.pellet@gmail.com>:

**Comment by NPellet** [comment]
Ok, further breaking changes with 1.12.0
If you're using the normal build of jsGraph it shouldn't change much. Most of it is internal cuisine.
All examples have been updated. The version comes along couple bug fixes I've encountered on the way.

But you need to pay attention that:
* Graph creation can no longer be asynchronous
* Shape creations are no longer asynchronous
* Shapes are by default locked and unselectable
* /!\ Plugins have been stripped of their "graph.plugin."

**Comment by NPellet** [comment]
Ah ok also you should now use ```graph.newShape( type, options );```

**Comment by targos** [comment]
OK it seems to work, thanks for the information.

I just have a question about `graph.newShape`.
I was using it like this: `graph.newShape(annotation, null, null, true);`
I understand that it should now be `graph.newShape(annotation.type, annotation);` but what about the other parameters from previous API? I do not remember their purpose.

**Comment by NPellet** [comment]
The last boolean was used to return the shape directly, without deferred.
It was useful is the shape is precompiled in the distribution source.
Now to use external shapes you need to load the file and register the shape
constructor

Graph.registerContructor("graph.shape.yourShapeName", yourConstructor);

and then graph.newShape("yourShapeName", {} );

So no more asynchronous shape creation.

2015-07-02 17:18 GMT+08:00 Michaël Zasso <notifications@github.com>:

**Comment by targos** [comment]
migration was done with success, thanks @NPellet !

**Comment by NPellet** [comment]
Good ! Thx for the fix

2015-07-16 21:24 GMT+08:00 Michaël Zasso <notifications@github.com>:
