### ISSUE TITLE
zoom in x problem

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#615]
The zoomed zone barely appears. 

Testcase: http://visualizer.epfl.ch/tiny/pxObwbnb7zSHGUN4beXo ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2Fb50564ac9d207212f8e5ae8167a5b107%2Fview.json&v=latest))

**Comment by andcastillo** [comment]
The spectrum is a peak table. For "continuos" data it works well.

**Comment by NPellet** [comment]
Likely relates to NPellet/jsGraph#47

**Comment by NPellet** [comment]
@targos, can you update jsGraph to 1.13.0 and tell me if @andcastillo's testcase is still problematic ?

**Comment by targos** [comment]
yes it is fixed, thanks !
