### ISSUE TITLE
Row selection model

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#619]
It is not enough to select "Row selection model" to be able to select many rows. The "edit" options has also to be activated. This does not seem normal

Testcase: http://visualizer.epfl.ch/tiny/YxwAhYgKwLD1UKuOciQD ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2Fcb8a3f4de3c6eef86332f89ed5e9d972%2Fview.json))

**Comment by stropitek** [comment]
This cannot be changed in the module, only in slickgrid. I thought of making editable the default and remove the option since you can configure each column to be editable independently (and default is not editable). But then we lose the possibility to make the table not selectable...
