### ISSUE TITLE
Switching view

### ISSUE THREAD

**Issue by JeffersonH44** [NPellet/visualizer#622]
When you change the view for another, it doesn't reload the global preferences libraries and just taking the previous view libraries, for example:

previous view:
ML -> 1 (version)

current view:
ML -> 3 (version)

it's supposed that will take the version of the current view but it's only taking the library of the previous one.

**Comment by targos** [comment]
Possibly related to #528

**Comment by stropitek** [comment]
Fixing #528 helps but still in the scenario where a global alias is used in the configuration of a code executor, the code executor has to be re-saved in order to actually use the change.

@targos can you look at this?

**Comment by targos** [comment]
I fixed the code executor
