### ISSUE TITLE
Allow highlight in panzoom

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#633]
For the image-js project I would like we have highlight in / out in panzoom module
The image tag would be like:

{
  type:'png'
  value:'http:.....'
  _highlight: [[1,1,1],[-1,1,-1],[2,-2,2]]
}

_highlight contains an array of array of either values of array.
The array of array is a matrix of the same size as the image.

When going over the image after a small debouncing the highlight event is send and simply call the corresponding value of the pixel hover based on the _highlight matrix

For highlight in, there should be a way to highlight all the pixels that corresponding to a specific value. Hope the speed will be ok with images that can be 10 M pixels ...

This will allow to focus in a slick grid to the detail information of a region of interest (ROI) and from a slick grid identify where is a specific region of interest.

**Comment by targos** [comment]
isn't it simpler on both sides to send a new image from slick grid that is the region of interest (with color inside and transparency outside) ?

**Comment by lpatiny** [comment]
It should be a 1D array : highlight

* convert highlight 1D array to an object
highlightID: {
width, height, shiftX, shiftY, data: [index]

On mouse over:
create ImageData: [R, G, B, A]

highlightID Hover = highlight [ width*y+x ]

**Comment by lpatiny** [comment]
Add a variableOut that contains the highlightID

**Comment by targos** [comment]
I see that you implemented it using an image element. We saw while developing the image library that a very slow step is `canvas.toDataURL`. Do you think it could be avoided by putting the canvas element in the DOM instead of an `<img>` ?
