### ISSUE TITLE
Allow css number and string type renderer?

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#634]
I would need to display value in a slick grids but in one row I would have many background colors. This is the result of elemental analysis match.

Would it be possible to allow:
`{type:"number", value: 123, _options:{css:{}}}` ?

**Comment by targos** [comment]
let's try first to change directly the css of the internal container for all types

**Comment by stropitek** [comment]
Just added the backgroundColor option for now. A css option would be too general by also allowing to break the layout of rendering
