### ISSUE TITLE
Couchdb2: Logout when using httpd authentication

### ISSUE THREAD

**Issue by David-Turbert** [NPellet/visualizer#638]
When I click on "Logged in as myuser Logout" I have this error: 
"Uncaught SyntaxError: Unexpected token <" in /couch/virago/home/index.html

**Comment by stropitek** [comment]
Fixed in 3423e8d0706b7601d7cec159ff451e68d4098ea9
The error is normal, jquery.couch expects a json and receives an html response from nginx telling you have to authentify. I'm handling this error by reloading the page so that the user is prompted with an authentification dialog
