### ISSUE TITLE
slickgrid not the same things if webservice is succes or not

### ISSUE THREAD

**Issue by David-Turbert** [NPellet/visualizer#641]
If the url of my webservice is false, the value does not change or if the url of webservice is true It works and the variable is empty

*Change the variable of the "webservice2" for a false return

example:
http://visualizer.epfl.ch/tiny/O2LbM4sjxZKUBety1C7Y

**Comment by stropitek** [comment]
Can you explain a bit more? What do you mean by the webservice being (returning?) true or false?
It works when what variable is empty?

**Comment by stropitek** [comment]
Are you sure the example is correct?
It is the same as for #642

**Comment by David-Turbert** [comment]
for the module "webservice2" change url with something like:
https://myfalseurl
If the webservice2 return success with code 200 the variable in the object editor was empty but in the other case wasn't.

I'm sure the example is correct and not the same than #642

**Comment by stropitek** [comment]
The webservice module will have no output value if the request failed. I think this is the expected behaviour. What else would you expect?

**Comment by stropitek** [comment]
If it is needed we could have a second variable out "on search error"

**Comment by stropitek** [comment]
@David-Turbert , any comments? Can I close this?

**Comment by David-Turbert** [comment]
not yet for me

**Comment by David-Turbert** [comment]
see http://visualizer.epfl.ch/tiny/vu0B1UYN57duOddmHMJG
