### ISSUE TITLE
pan - zoom module. add an option for maximum 100%

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#646]
Add the possibility to display the image to maximum 100%.

Currently for small images they are scaled to 100% of the surface and this does not always look nice.

Don't know if those css rules may be of any help
            width:100%;
            height:100%;
            max-width:500px;
            max-height:500px;

**Comment by stropitek** [comment]
If I understand you would like the image to be scaled but only up to a certain point? (maximum X px)

**Comment by lpatiny** [comment]
I would like that when it is a new image by default it could be scaled down to fit the module size but not scaled up to more than 100%
