### ISSUE TITLE
scatter3d not working in chrome 43

### ISSUE THREAD

**Issue by stropitek** [NPellet/visualizer#649]
Points appear very small (independent of the selected size)
Working in chrome 42 and chrome 44-beta
May be a bug in chrome...

http://www.cheminfo.org/?viewURL=http%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo%2F59dec54d14e5e206142256823ef36bfe%2Fview.json&loadversion=true&fillsearch=Scatter+3D+-+Big+data

**Comment by targos** [comment]
chrome 44 is stable now, people will upgrade automatically
