### ISSUE TITLE
Problems displaying XY arrays

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#656]
I reported this problems many weeks ago. When you zoom over a discrete serie nothing is displayed. Second, the jcamps usually does not appear on load. You need to open the preferences and save to get the jcamp displayed.

Testcase: http://visualizer.epfl.ch/tiny/8FfcssG34qjdRrKItpu9 ([Original URL](http://www.lactame.com/visualizer/latest/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FBPynKvEevB%2Ftest%40patiny.com%2FDemo%2FSpectra%2FNMR%2FGSD%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FgACTvXSnRB%2Ftest%40patiny.com%2FDemo%2FSpectra%2FNMR%2FGSD%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json))

**Comment by NPellet** [comment]
That's a jsGraph bug. A ticket there will be more appropriate

**Comment by targos** [comment]
I do not see any existing issue about that. Can you link to it here if there is one ?
About the second issue, I cannot reproduce it and this is the first time I hear about it. Do you have a reliable way to trigger the problem ?

**Comment by andcastillo** [comment]
Here is the first report that you tagged as bug: #615
The second problem could be related with the timeout. Perhaps the module is ignoring the timeout parameter or something else is going wrong. Also in the error is say that the timeout is set to 5000 secs!. I supposed it was in milliseconds. 

DataURL: getting http://script.epfl.ch/script/HD/Load/5U6zjggSFn?filename=test%40patiny.com%2FDemo%2FSpectra%2FNMR%2FGSD%2Fh1_14.jdx with force set to false and timeout to 5000
/visualizer/latest/init.js:33 DataURL: Looking in LRU for http://script.epfl.ch/script/HD/Load/5U6zjggSFn?filename=test%40patiny.com%2FDemo%2FSpectra%2FNMR%2FGSD%2Fh1_14.jdx with timeout of 5000 seconds
/visualizer/latest/init.js:33 DataURL: Looking into LRU for http://script.epfl.ch/script/HD/Load/5U6zjggSFn?filename=test%40patiny.com%2FDemo%2FSpectra%2FNMR%2FGSD%2Fh1_14.jdx
/visualizer/latest/init.js:33 DataURL: Found http://script.epfl.ch/script/HD/Load/5U6zjggSFn?filename=test%40patiny.com%2FDemo%2FSpectra%2FNMR%2FGSD%2Fh1_14.jdx in local DB. Timeout: 1438033789763
/visualizer/latest/init.js:33 DataURL: URL is over timeout threshold. Looking by AJAX
/visualizer/latest/init.js:33 DataURL: Looking for http://script.epfl.ch/script/HD/Load/5U6zjggSFn?filename=test%40patiny.com%2FDemo%2FSpectra%2FNMR%2FGSD%2Fh1_14.jdx by AJAX
