### ISSUE TITLE
spectra displayer not showing multiple charts

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#659]
Testcase: http://visualizer.epfl.ch/tiny/0nTiZoKWMzpc02y7p76L ([Original URL](http://www.cheminfo.org/static/index.html?viewURL=http%3A%2F%2Fwww.cheminfo.org%2Fclp%2Fc%2F6df02a8df5f5f1729f67350b463050ea%2Fview.json&v=HEAD))

**Comment by maasencioh** [comment]
test it in HEAD
