### ISSUE TITLE
Spectra Displayer doesn't display the values in the 1D XY array.

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#660]
Testcase: http://visualizer.epfl.ch/tiny/92oakEu30Wb5xVP14CUq ([Original URL](http://visualizer.epfl.ch/c/home/index.html?v=v2.26.0&viewURL=%2Fc%2F4361c134eb36eff59b0388449ff6fd99%2Fview.json))

**Comment by targos** [comment]
see #661
