### ISSUE TITLE
spectra displayer is blank with 1d xy input

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#661]
Blank spectra displayer without error messages. It worked ok in [v2.25.0] (http://www.lactame.com/visualizer/v2.25.0/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FBPynKvEevB%2Ftest%40patiny.com%2FDemo%2FSpectra%2FNMR%2FGSD%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FgACTvXSnRB%2Ftest%40patiny.com%2FDemo%2FSpectra%2FNMR%2FGSD%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json)

Testcase: http://visualizer.epfl.ch/tiny/XRvxnbdKGzK6UAk6plhj ([Original URL](http://www.lactame.com/visualizer/v2.26.0/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FBPynKvEevB%2Ftest%40patiny.com%2FDemo%2FSpectra%2FNMR%2FGSD%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FgACTvXSnRB%2Ftest%40patiny.com%2FDemo%2FSpectra%2FNMR%2FGSD%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json))

**Comment by NPellet** [comment]
Is it a jsGraph bug ?

**Comment by targos** [comment]
don't know yet, I will investigate tomorrow morning
