### ISSUE TITLE
grapph temporal - time axis

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#664]
Timestamp axis is not working

Testcase: http://visualizer.epfl.ch/tiny/AZB9a6Rj9KVaAVFXov1b ([Original URL](http://www.lactame.com/visualizer/latest/index.html?viewURL=http://visualizer.epfl.ch/x/9niUbLWdWEKil8r66cV5/view.json&dataURL=http://visualizer.epfl.ch/x/9niUbLWdWEKil8r66cV5/data.json))

**Comment by NPellet** [comment]
Issue likely from jsGraph. Fixed in v1.12.4-12

**Comment by targos** [comment]
Ref: https://github.com/NPellet/jsGraph/issues/48

**Comment by targos** [comment]
should be fixed by 250d80dd02d320e3f8af5526daf020209687c6af
