### ISSUE TITLE
node version not working

### ISSUE THREAD

**Issue by andcastillo** [NPellet/visualizer#669]
The current version of the visualizer is not compatible with the the visualizer-node project. The components folder has moved.

**Comment by targos** [comment]
The components folder has never moved, and visualizer-node is just a web server, it doesn't care about where are the files.
What exactly is your problem?

**Comment by andcastillo** [comment]
Has never changed? 
![screen shot 2015-08-06 at 11 52 41 pm](https://cloud.githubusercontent.com/assets/3810292/9128956/97403f70-3c96-11e5-8302-c93533c67d80.png)
![screen shot 2015-08-06 at 11 54 23 pm](https://cloud.githubusercontent.com/assets/3810292/9129002/2d4ba6da-3c97-11e5-8fb8-aae612737369.png)

And the problem is that after I go http://10.0.0.9:8000 it could not find  "http://10.0.0.9:8000/visualizer/src/components/

**Comment by targos** [comment]
Components are not checked out anymore in git. You must use `npm install` to download them.
