### ISSUE TITLE
jpath selection of variable out of code executor to slow

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#670]
If you take the cat image you are not really able to select the jpath of variable out in the code executor

Testcase: http://visualizer.epfl.ch/tiny/ZjT4NvCdBF7YVKihKs0M ([Original URL](http://www.cheminfo.org/static/index.html?viewURL=http%3A%2F%2Fwww.cheminfo.org%2Fclp%2Fc%2F6df02a8df5f5f1729f67350b462a07ad%2Fview.json))

**Comment by targos** [comment]
what do you mean by "to slow" ?

**Comment by lpatiny** [comment]
Seems there is a introspection of the object and because of the complexity the introspection is too slow (10s or more per level)

**Comment by targos** [comment]
what kind of object are you exporting ?

**Comment by targos** [comment]
ping

**Comment by targos** [comment]
the typed array is not detected and all elements are traversed.

**Comment by targos** [comment]
I can't reproduce, please reopen with a testcase if it happens again
