### ISSUE TITLE
Single value module do not display the value

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#673]
This view requires an open spectrophotometer to test in a chrome app.

Could be that the result contains number and selecting some jpath send it as a DataString but with a number as value and not a string.

Testcase: http://visualizer.epfl.ch/tiny/gy5Or9ySXEyg6ncPfhc3 ([Original URL](http://www.cheminfo.org/flavor/spectrophotometer/index.html))

![temp](https://cloud.githubusercontent.com/assets/1484241/9292307/b19642c8-43f0-11e5-9a60-f0549c32f328.png)

**Comment by lpatiny** [comment]
This was due by a conflict of function. I had redefined postMessage for another script in window.
