### ISSUE TITLE
Slick grid and delete row

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#674]
When the option "Can delete row" is selected it does not seem possible to delete the row (there should be a little trash icon ?)

Testcase: http://visualizer.epfl.ch/tiny/HZ4EXFrXjDBYutiZQPXb ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2Fe1f16b237a79ee04363ade8bcea89add%2Fview.json))

**Comment by stropitek** [comment]
This option seems superfluous, I will remove it.

You have to select "can delete row" but also in the "auto column" section you have to select "Column for one-click removal of a line"

**Comment by stropitek** [comment]
Actually "can delete row" is not used anymore. I will remove it.
