### ISSUE TITLE
JsChart bug when changing the spectra and vertical scale

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#675]
When replacing an existing spectrum for which minY / maxY are different the vertical axis value does not change (or at least is not redraw). If you change again the data the axis value of the previous spectrum is displayed.

Testcase: http://visualizer.epfl.ch/tiny/Y00J8B5uYgBBbRytid1a ([Original URL](http://visualizer.epfl.ch/c/home/index.html?viewURL=%2Fc%2F4361c134eb36eff59b0388449f099024%2Fview.json))

**Comment by lpatiny** [comment]
@NPellet 
It seems to be still the case in the last version. You may check the example with the head on
http://visualizer.epfl.ch/tiny/z02IFTKMvXwy9KsCcqd0

**Comment by NPellet** [comment]
Yeah actually I didn't get the bug report. I'd be happy to fix it but I
need something easier to understand...

2015-09-02 15:54 GMT+02:00 lpatiny <notifications@github.com>:

**Comment by lpatiny** [comment]
Sorry indeed this view was a mess ... Here should be easier.
http://visualizer.epfl.ch/tiny/KSGHAjdOZ7XCpHrjpqrG

**Comment by lpatiny** [comment]
Just change a x or y value. You will see that the axis will be scaled after the next change

**Comment by NPellet** [comment]
Yeah ok I see the issue here. It's definitely a bug on my side.

2015-09-02 16:20 GMT+02:00 lpatiny <notifications@github.com>:

**Comment by NPellet** [comment]
Impossible de reproduce the bug on my side though (which makes sense, it's quite obvious)

I'm not saying there's no bug because jsGraph shouldn't behave like that.

@targos, can you tell me what exactly are the methods called in that case ?

**Comment by NPellet** [comment]
News on that ?

**Comment by lpatiny** [comment]
We check that this bug can also be reproduced with a simple 1D array
http://visualizer.epfl.ch/tiny/NqJa6zgf7mcJsnhoTfAV

**Comment by targos** [comment]
@NPellet I'm looking into it right now

**Comment by targos** [comment]
OK it seems to be related to changes in the `redraw` method. I pushed a fix but I am not sure it is entirely correct.

@NPellet can you look at https://github.com/NPellet/visualizer/blob/aa903cf7bcbc168a5d5f981df35e7e0f5df62dd1/src/modules/types/science/spectra/spectra_displayer/view.js#L302-L333 ?
It is called when a serie has new data. I think there is still a bug when `fullOut` is set to `xAxis` or `yAxis` (axes are redrawn but not the series). should I call another method in these cases ?

**Comment by NPellet** [comment]
So technically when the boundaries of the axes have changed, the series
have to be redrawn (jsGraph should take care of it). That includes the
setMinMaxToFitSeries method.

So it looks good to me. If this implementation bugs, then it's definitely
my issue.


2015-09-07 14:21 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by NPellet** [comment]
Ah ok when I compare to the old implementation it makes sense that it didn't work.
In fact it should never have worked :D
redraw() was to be called after setMinMaxToFitSeries()

Anyway, glad to see that this was solved.

**Comment by targos** [comment]
Just tested it again and it's working as expected.
