### ISSUE TITLE
spectra displayer : style and error

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#677]
It would be nice to improve the chart-schema to have
* dx : error bar on x axis, could be
  * [1,2,1,2] - same error on top and bottom
  * [[1,2],[2,3],[2,4],[1,2]] - error bar
  * ? - error bar + box plot
* dy
How to display the mean ?

* style: {strokeWidth:2, strokeColor: XXX}

https://github.com/cheminfo/json-chart/blob/master/chart-schema.json

**Comment by targos** [comment]
Closing. Issue moved to the jsgraph project
