### ISSUE TITLE
slickgrid: problem in column sorting

### ISSUE THREAD

**Issue by targos** [NPellet/visualizer#678]
* Go to http://www.cheminfo.org/wikipedia
* Open the 'Browse errors' layer
* Try to sort the 'SMILES with errors' table

The sorting works for the first 2 columns but not for the last one

**Comment by stropitek** [comment]
I think this has been solved since 2.18.0
Ref: #522

**Comment by targos** [comment]
oh you are probably right, I forgot that this application has an old version of the visualizer...
I will try to update it
