### ISSUE TITLE
spectra displayer: display bug when zooming in

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#679]
When zooming in markers don't disappear

ALso the legend shows chart and chart-1, when there is only chart

Testcase: http://visualizer.epfl.ch/tiny/tf5x2M5PprvWn1ttJVE7 ([Original URL](http://www.lactame.com/visualizer/latest/))

**Comment by NPellet** [comment]
@targos: this is not a jsGraph issue (at least in my head version, which I
just released ( v1.13.1-0))​

**Comment by targos** [comment]
The legends adds one line for each serie and you have 2 series so this is normal

**Comment by targos** [comment]
@NPellet the zoom problem is still present with v1.13.1-0.
You can see it here: http://direct.lactame.com/visualizer/HEAD/index.html?viewURL=http://visualizer.epfl.ch/x/tf5x2M5PprvWn1ttJVE7/view.json&dataURL=http://visualizer.epfl.ch/x/tf5x2M5PprvWn1ttJVE7/data.json

**Comment by NPellet** [comment]
For the legend, you can use the .fixSeries() method. Allows you to select
which ones to display.

2015-08-20 9:37 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by NPellet** [comment]
For the markers bug, are you using .draw() or .redraw();.drawSeries() ?

2015-08-20 9:42 GMT+02:00 Norman Pellet <norman.pellet@gmail.com>:

**Comment by targos** [comment]
None of them ? The zoom is handled internally by jsgraph when the mouse action is done

**Comment by targos** [comment]
to draw the serie at the beginning we use
```js
graph.redraw();
graph.autoscaleAxes();
graph.drawSeries();
```

**Comment by NPellet** [comment]
Ok that has nothing to do but use autoscalAxes then draw().
Can you give me the data you are using ?

**Comment by targos** [comment]
serie options:
```json
{
  "trackMouse": true,
  "markersIndependant": true,
  "lineToZero": false,
  "useSlots": true,
  "strokeWidth": 1
}
```

data:
```json
[
  1440000000000,
  28.330000000000002,
  1439996400000,
  28.36,
  1439992800000,
  28.22,
  1439989200000,
  28.400000000000002,
  1439985600000,
  28.45,
  1439982000000,
  29.69,
  1439978400000,
  30.22,
  1439974800000,
  30.18,
  1439971200000,
  30.330000000000002,
  1439967600000,
  30.330000000000002,
  1439964000000,
  30.26,
  1439960400000,
  30.37,
  1439956800000,
  30.3,
  1439953200000,
  30.14,
  1439949600000,
  30.16,
  1439946000000,
  29.96,
  1439942400000,
  29,
  1439938800000,
  29.2,
  1439935200000,
  28.76,
  1439931600000,
  28.62,
  1439928000000,
  28.900000000000002,
  1439924400000,
  28.92,
  1439920800000,
  27.740000000000002,
  1439917200000,
  27.47,
  1439913600000,
  27.55,
  1439910000000,
  27.05,
  1439906400000,
  27.26,
  1439902800000,
  27.810000000000002,
  1439874000000,
  29.63,
  1439870400000,
  29.79,
  1439866800000,
  29.85,
  1439863200000,
  30.05,
  1439859600000,
  30.060000000000002,
  1439856000000,
  30.02,
  1439852400000,
  30.150000000000002,
  1439848800000,
  30.22,
  1439845200000,
  30.14,
  1439841600000,
  30.21,
  1439838000000,
  30.310000000000002,
  1439834400000,
  30.25,
  1439830800000,
  30.26,
  1439827200000,
  30.42,
  1439823600000,
  30.43,
  1439820000000,
  30.25,
  1439816400000,
  30.23,
  1439812800000,
  30.150000000000002,
  1439809200000,
  29.88,
  1439805600000,
  29.75,
  1439802000000,
  29.8,
  1439798400000,
  29.63,
  1439794800000,
  29.53,
  1439791200000,
  29.66,
  1439787600000,
  29.69,
  1439784000000,
  29.67,
  1439780400000,
  29.82,
  1439776800000,
  29.88,
  1439773200000,
  29.84,
  1439769600000,
  29.95,
  1439766000000,
  30.060000000000002,
  1439762400000,
  30.01
]
```

**Comment by NPellet** [comment]
Ok first issue: your x data is monotoneous, but descending. This has not been really tested (and in fact it bugs). I will try to fix it...

In the meantime for the markers you can use  v1.13.1-1

**Comment by targos** [comment]
Seems fixed on HEAD
