### ISSUE TITLE
database issue

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#683]
i have visited your site and i found it useful for my work. but there is no link to either view or download database. if you can make it available for user it will be of great help.

Testcase: http://visualizer.epfl.ch/tiny/nEFKmcTVlmSA7ZY2GwT3 ([Original URL](http://www.cheminfo.org/static/index.html?viewURL=http%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo%2F554613d831e22b95c6eb805bec1437a2%2Fview.json%3Frev%3D23-de950441769fe1292a039e879ffb7a70))

**Comment by lpatiny** [comment]
If you are speaking about the database containing all the views and datas (couchdb database) the link is provided on the home page as well as the instruction to have a local copy.
