### ISSUE TITLE
Bug in onde module

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#684]
If you make an "in-place" modification (like here changing C10 to C100) the value change correctly in the variable.

However if you click in the preferences of onde module and validate them. Then you change the C100 to C1000 it is a new variable that is apparently changed.

Testcase: http://visualizer.epfl.ch/tiny/2dgopnHDNv42kHJqrINf ([Original URL](http://www.lactame.com/visualizer/v2.26.3/index.html?viewURL=http://visualizer.epfl.ch/x/qhZafX65vsVauC0vXJ71/view.json&dataURL=http://visualizer.epfl.ch/x/qhZafX65vsVauC0vXJ71/data.json))

**Comment by stropitek** [comment]
Can you help me reproduce in a simpler test case?
Not able to reproduce in http://visualizer.epfl.ch/tiny/x2NtvsetHwTm0eOmvWHF
