### ISSUE TITLE
Would be nice ... if slick grid ... could implement sprintf

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#689]
I have problems displaying value in slick grid and in particular numbers because I have many digits and would like to be able to format those numbers using sprintf (like implement in the single value module).

Would it be "easy" to allow another "Formatter" that would be "sprintf" and that would allow the format as an option. This would imply I guess to add a column "Formatter options"

**Comment by lpatiny** [comment]
In the meantime there is a kind of work around but it actually change the data.

You can use the filter from the slick-grid options and have something like:

row.mass=Math.round(row.mass*1000)/1000;
row.intensity=Math.round(row.intensity*1000)/1000;

**Comment by targos** [comment]
you can also use the options of the number type renderer

**Comment by stropitek** [comment]
@lpatiny can I close this? As @targos said the type renderer can be used and I see no reason to have a specific formatter in slickgrid for that

**Comment by lpatiny** [comment]
In the preferences of the slick grid it would be nice to be able to specify the options of the renderer

The options would be a new column in the preferences. Can be in the format
toFixed:5
or 
{toFixed:5}
If it is not starting with a curly bracket it should be wrapped before being evaluated.

https://github.com/NPellet/visualizer/issues/689
