### ISSUE TITLE
Why there is "x10" in the label of jsgraph (spectra displayer)

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#697]
When adding a label for the axes 'x10' is appended. In this case I think it should not be present. Quite sure for the mass and very likely for the peak width.

Testcase: http://visualizer.epfl.ch/tiny/iZimGIa0K5wi8TV2FS9w ([Original URL](http://www.lactame.com/visualizer/v2.27.0/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FBFFaGXg0QI%2Ftest%40patiny.com%2FResearch%2FMass%2FPeakWidthSimple%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FEomhuTsSp7%2Ftest%40patiny.com%2FResearch%2FMass%2FPeakWidthSimple%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json))

**Comment by NPellet** [comment]
Should also be closed with the latest version of jsGraph

2015-09-01 13:50 GMT+02:00 visualizer-feedback <notifications@github.com>:

**Comment by lpatiny** [comment]
Fixed on the head

**Comment by targos** [comment]
it should be fixed in latest, the head has nothing more
