### ISSUE TITLE
How to deal with errors in the worker ?

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#698]
In this view we start chemcalc process as a worker.

However in this specific example because withTop is larger than widthBottom an error is generated. The consequence is that the call back is never called.

Because I normally use in the callback a counter to find out when all the process are finished this procedure never ends.

Testcase: http://visualizer.epfl.ch/tiny/5HAvg8T2F3APF1pPAf0z ([Original URL](http://www.lactame.com/visualizer/latest/index.html?viewURL=http://visualizer.epfl.ch/x/Iut9yIdIgETXk02URdfS/view.json&dataURL=http://visualizer.epfl.ch/x/Iut9yIdIgETXk02URdfS/data.json))

**Comment by targos** [comment]
fixed in https://github.com/cheminfo-js/worker-manager/releases/tag/v0.1.0
please file issues in https://github.com/cheminfo-js/worker-manager/issues if you find other bugs
