### ISSUE TITLE
X label is not visible

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#701]
X label under the axe is nearly completely hidden.

Testcase: http://visualizer.epfl.ch/tiny/5Ad9ZNtuoEBg95B6YDuU ([Original URL](http://visualizer.epfl.ch/c/home/index.html))

**Comment by lpatiny** [comment]
@NPellet Would this problem be related to JsGraph ?

**Comment by NPellet** [comment]
Hmmm probably, but likely because there are no ticks

2015-09-09 13:18 GMT+02:00 lpatiny <notifications@github.com>:

**Comment by lpatiny** [comment]
Sorry the chart data were not there .... here is the test case with some data, but there is the same problem
http://visualizer.epfl.ch/tiny/yrzr40M56Fcny14ytjiM

**Comment by NPellet** [comment]
Damn, that is weird... That is for all the graphs in the visualizer ?

2015-09-09 14:32 GMT+02:00 lpatiny <notifications@github.com>:

**Comment by targos** [comment]
It seems to be a recent regression. It is fine on http://www.lactame.com/visualizer/v2.27.0/index.html?viewURL=http://visualizer.epfl.ch/x/yrzr40M56Fcny14ytjiM/view.json&dataURL=http://visualizer.epfl.ch/x/yrzr40M56Fcny14ytjiM/data.json

**Comment by NPellet** [comment]
I indeed changed the code that computes the height of the axis, but could
not see any effect in my tests. Ok I will investigate and let you guys know.

2015-09-09 14:34 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by NPellet** [comment]
This can be closed with v1.13.3-17
