### ISSUE TITLE
Slick grid

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#716]
When adding a new row the variable out should be triggered to erase the current variables.

Testcase: http://visualizer.epfl.ch/tiny/77VKRxvxKZfbO4jBMsdE ([Original URL](http://direct.lactame.com/visualizer/HEAD/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FWyrccHtLiV%2Ftest%40patiny.com%2FDatabases%2FReactions%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FLrdoph6Kvd%2Ftest%40patiny.com%2FDatabases%2FReactions%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json))

**Comment by stropitek** [comment]
You should create a new variable out on the event "row added" and set it to "reactions" as well. It will overide the variable that was created by the click.

There is no reason the variable on click event should be changed by slickgrid if the user has not clicked...
