### ISSUE TITLE
Spectra displayer: incorrect time axis

### ISSUE THREAD

**Issue by stropitek** [NPellet/visualizer#718]
When using the time axis in jsgraph there are several problems:
* The date is not displayed, only the time
* The ticks that separate days are often not on midnight
* The time shown on the axis does not correspond to the timestamp provided. Also the time shown on the axis for the same timestamp is different if the length of the data is different...

Testcase: http://visualizer.epfl.ch/tiny/hAwlDmhRlEwfse68Lyq6 ([Original URL](http://localhost/visualizer/src/index.html?config=%2Fvconfigs%2Fcouchdb.json&debug=5&viewURL=http%3A%2F%2Flocalhost%2Flocalcouch%2Fmyviews%2Fd18507daf829234f05c8e2416a21f1d6%2Fview.json))

**Comment by NPellet** [comment]
Did you follow the online example ?

**Comment by targos** [comment]
You mean http://www.jsgraph.org/examples/axis/timeaxis.js/ ?
What is special about this example ? We set `type: time` for the X axis
