### ISSUE TITLE
We adding the option Make text selectable in one module display value all the text from all the modules are selected

### ISSUE THREAD

**Issue by thegodone** [NPellet/visualizer#719]
using the following process either double click on the module text or crtl+A than ctrl + v gave all the text selected in all the modules

**Comment by targos** [comment]
what platform ? I cannot reproduce on OSX with the following view, double click works as expected: http://visualizer.epfl.ch/tiny/mbNiDQ2JTBbxVLYSqNne

**Comment by targos** [comment]
Also unable to reproduce on Fedora and Window 10 (tested Chrome and Edge)

**Comment by thegodone** [comment]
Chrome WINDOWS 8.1

Envoyé de mon iPhone

**Comment by targos** [comment]
If this is still an issue, please explain in more details how to reproduce

**Comment by thegodone** [comment]
Bonjour NPellet/visualizer,
guillaume godin vous a laissé un message sur IQ Elite 
Cliquez ici a.iqelite.com/j/2vBDJ3/x4t/?hg=JSNjELOxI7 pour lire votre message 


L'équipe d'IQ Elite



---------------------------------------------------------------------------
Ce message est destiné à reply@reply.github.com. Si vous ne souhaitez pas recevoir d'autres messages de la part de IQ Elite, veuillez cliquer sur ce lien : a.iqelite.com/common/unsubscribe/?code=35097059&email=reply@reply.github.com.&hg=JSNjELOxI7
IQ Elite est un service de IQ Elite S.L., dont le siège se trouve à : C/ Gran De Gràcia 15, 1a 1a, 08012 Barcelone, Espagne. 
---------------------------------------------------------------------------
