### ISSUE TITLE
Slick grid and new out event : row has been activated

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#720]
We would like to edit the table in the bottom left and each time we change of row (based on tabulation for example) that the variables out can be changed.

This could be done with an event like 'on row activated' that could be triggered. This event should probably also be triggered if the selection is coming from an actionIn. What about the focus on highlight ? I would say the row is not activate

Testcase: http://visualizer.epfl.ch/tiny/67ctWq2qnSGwJKlsGahW ([Original URL](http://www.lactame.com/visualizer/HEAD/index.html?views=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2Fx6sVlM0Nne%2Ftest%40patiny.com%2FTeaching%2FOrganicChemistry%2FIupac%2F.views&results=http%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FXgf59L3BPl%2Ftest%40patiny.com%2FTeaching%2FOrganicChemistry%2FIupac%2F.results&viewBranch=Master&resultBranch=Master&config=http%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json))

**Comment by stropitek** [comment]
Have you seen that the event already exists?

**Comment by lpatiny** [comment]
Sorry indeed it works perfectly.
