### ISSUE TITLE
Zoom does not work on scatter plot

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#724]
The axis change but not the data

Testcase: http://visualizer.epfl.ch/tiny/hZjbUMMF9GXKOiI8JH5q ([Original URL](http://visualizer.epfl.ch/c/home/index.html))

**Comment by NPellet** [comment]
Hey this is still valid right ? Having the same here...

**Comment by NPellet** [comment]
@targos, please update to jsGraph 1.13.3-19 and the bug will disappear
