### ISSUE TITLE
Dynamic change of cells

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#732]
When adding a molecular formula and hitting "tab" the value is not updated directly and I don't know why.

 
Testcase: http://visualizer.epfl.ch/tiny/k7YDJ0QiC1xASR9y5x3Y ([Original URL](http://visualizer.epfl.ch/c/home/index.html))

**Comment by stropitek** [comment]
You change cells asynchronously. Therefore you change them when the grid has already been re-rendered. You need to re-render them yourself by calling internal slickgrid methods. I can make that easier by adding ```rerender()``` to the script execution context.

**Comment by stropitek** [comment]
```rerender()``` added in 76935ee273f767b24b8f39736b7367c02348fa40
http://www.lactame.com/visualizer/HEAD/index.html?viewURL=http://visualizer.epfl.ch/x/8Jq0MZKCMWuDlfaEkFA8/view.json&dataURL=http://visualizer.epfl.ch/x/8Jq0MZKCMWuDlfaEkFA8/data.json
