### ISSUE TITLE
slick grid and event

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#735]
When adding a new row (entering a value in the cell) some events are generated:
rowsChanged, newRow, rowsSelected

However the event cellChanged is not thrown. I think it should be thrown at after all the other (or at least after newRow)

http://visualizer.epfl.ch/tiny/bwSzyiET1TZBpTvgFAzb

**Comment by stropitek** [comment]
I think I would rather add a ```column``` property on ```newRow``` so that we know which column has been edited in the new row. It covers more cases. Imagine an application where we want to know about changed cells but only in existing rows.
