### ISSUE TITLE
inplace edition for single value module

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#741]
It could be easy ? To allow in place edition for single value module.

This feature could only be active for type="string" or "number"

It could be "in-place" or have a variable out.

https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_Editable

**Comment by stropitek** [comment]
Fixed in e978ed8f649a7223c6c15912ee8fe300a0fd82ad and 30ad424e53cd17a89d59dcedf92f1455810e393d
