### ISSUE TITLE
Bug with jsChart module ?

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#742]
When we click on "Test file" the file is parsed in the Parser layer and a chart object is created.

This chart object is expected to be displayed as an experimental spectrum but it seems not to work correctly. 

If you click a second time there is an error message. Could this be related to annoation ?

Testcase: http://visualizer.epfl.ch/tiny/fSRWtiEZzEA3RVdZa7n3 ([Original URL](http://www.lactame.com/visualizer/v2.28.4/index.html?viewURL=http://visualizer.epfl.ch/x/h21uCYtHDphzkCQAqZSZ/view.json&dataURL=http://visualizer.epfl.ch/x/h21uCYtHDphzkCQAqZSZ/data.json))

**Comment by lpatiny** [comment]
It is not a bug in js-chart but in the "chart" converter:
components/json-chart/dist/json-chart
That does not deal correctly with an array with no values

**Comment by targos** [comment]
Looks like it's fixed on HEAD
