### ISSUE TITLE
number type renderer and dates

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#743]
Would be nice in the number type renderer to allow this number to be an epoch and be able to format it directly. Like that a slick grid column containing epoch could be trivially be rendered.
* add the library: http://arshaw.com/xdate/
* allow in number renderer a new options: "dateFormat" that accepts directly the formatString of the 'toString' method of XDate library
``` javascript

var a=new XDate(123456);
a.toString('yyyy-MM-dd')
"1970-01-01"
```

**Comment by targos** [comment]
why use a library when date formatting is standard in JS?

**Comment by lpatiny** [comment]
Didn't know. How you can specify the date format in pure javascript ? This library allows the classical unix formatting fields:
fff	milliseconds, 3-digits
s	seconds
ss	seconds, 2-digits
m	minutes
mm	minutes, 2-digits
h	hours, 12-hour clock
hh	hours, 12-hour clock, 2-digits
H	hours, 24-hour clock
HH	hours, 24-hour clock, 2-digits
d	date number
dd	date number, 2-digits
ddd	day name, 3-characters (like "Sun")
dddd	day name, full (like "Sunday")
M	month number (Jan=1, Feb=2, etc)
MM	month number, 2-digits
MMM	month name, 3-characters (like "Jan")
MMMM	month name, full (like "January")
yy	year, 2-digits
yyyy	year, 4-digits
t	a/p
tt	am/pm
T	A/P
TT	AM/PM
z	timezone offset hour (like "-7") or "Z"
zz	timezone offset hour, 2-digits (like "-07") or "Z"
zzz	timezone offset hour, 2-digits, and minutes (like "-07:00") or "Z"
w	ISO week number
ww	ISO week number, 2 digits
S	day-of-week ordinal (like "st", "nd", "rd")
i	ISO8601 format, without a timezone indicator
u	ISO8601 format, with a timezone indicator

**Comment by stropitek** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat

**Comment by lpatiny** [comment]
Seems this library still make sense because it would really easy to format a date even in the slick grid for which a "small" field is available for options.

**Comment by stropitek** [comment]
I would suggest using [momentjs](http://momentjs.com/)

I like  the possibility to format as a relative date like '3 days ago'

It's also seem to have broader support that XDate

**Comment by lpatiny** [comment]
As long as it accepts the linux format it is ok

**Comment by stropitek** [comment]
The docs don't say it's the linux format but it seems extremely similar: http://momentjs.com/docs/#/displaying/
