### ISSUE TITLE
Add flags in visualizer ?

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#744]
https://github.com/lipis/flag-icon-css

MIT license that looks cool and seems easy to use

**Comment by stropitek** [comment]
Fixed

**Comment by David-Turbert** [comment]
did you have an example ?

**Comment by stropitek** [comment]
http://www.cheminfo.org/Tutorial/6._Renderer/6.9_Flags/index.html?viewURL=https%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo-public%2F90b4b872d2f4208e2611611c57d9736f%2Fview.json
