### ISSUE TITLE
JsGraph and large dataset slow down

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#747]
Using JsGraph with over 10000 points require to use the optimize by slot and the monotoneous option.
This allows to display quickly a set of 1 million points.

However when we zoom in if the number of points displayed is less than the size of the jsGraph module the module slows down. This can easily be checked using vertical scaling.

Norman told me that this was fixed in the last version of JsGraph.

http://visualizer.epfl.ch/tiny/N1OIwlXdePki92Lwpjxx

**Comment by NPellet** [comment]
Well I said maybe, if it's what I think it is...

2015-11-08 6:47 GMT+01:00 lpatiny <notifications@github.com>:

**Comment by lpatiny** [comment]
It was fixed in the recent release indeed and even 1e7 points work ! Thanks !

**Comment by NPellet** [comment]
Cool :)

2015-11-09 10:06 GMT+01:00 lpatiny <notifications@github.com>:
