### ISSUE TITLE
JsGraph avec vertical scaling

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#748]
JsGraph stops vertical scaling if the mouse touch the spectrum.

Don't know if this is the expected behaviour @NPellet ?

http://visualizer.epfl.ch/tiny/lB93FU63U96Q2mINLXWj

**Comment by NPellet** [comment]
This is a jsGraph issue indeed

2015-11-08 6:53 GMT+01:00 lpatiny <notifications@github.com>:

**Comment by targos** [comment]
I think it's fixed on HEAD
