### ISSUE TITLE
Slick grid create a new row from empty array

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#762]
The event new row is not thrown if the starting array is empty

http://visualizer.epfl.ch/tiny/zks68h7RijaTVT02Rtfd

**Comment by stropitek** [comment]
In your example I cannot add a new row because the column is not editable... When starting from an empty array, you have to specify an editor other than 'based on type' to make adding a new row work

**Comment by lpatiny** [comment]
Indeed sorry, it works perfectly. Many thanks !
