### ISSUE TITLE
jsgraph : annotations are not working anymore

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#765]

**Comment by targos** [comment]
cc @NPellet the error is inside jsgraph.
See http://www.lactame.com/visualizer/src/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/spectra2D/view.json&dataURL=../testcase/data/spectra2D/data.json

**Comment by NPellet** [comment]
Well obviously jsgraph should crash more gracefully. However this is unlileky a jsGraph error (not looked in details). This happens when no axis has been set to the serie for some reason. Possible ?

**Comment by NPellet** [comment]
Can you actually post the stack trace to a jsgraph issue ? Your fix is ok but still it should not crash

**Comment by targos** [comment]
I think it was like this: http://www.lactame.com/visualizer/v2.35.1/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/spectra2D/view.json&dataURL=../testcase/data/spectra2D/data.json
