### ISSUE TITLE
jsgraph and major / minor grid

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#766]
Would be nice to have different style for major and minor grid. It seems to be the same currently.

http://visualizer.epfl.ch/tiny/JsMIRcOaYkREHpMciqw2

**Comment by targos** [comment]
@NPellet is that configurable?

**Comment by NPellet** [comment]
Yes to some extend... I think the color mostly. @lpatiny do you want
thickness opacity and dasharray ?

**Comment by NPellet** [comment]
Try
```
axis.setPrimaryGridColor( string );
axis.setSecondaryGridColor( string );
axis.setPrimaryGridWidth( number );
axis.setSecondaryGridWidth( number );
axis.setPrimaryGridOpacity( number );
axis.setSecondaryGridOpacity( number ); 
```

**Comment by NPellet** [comment]
(since v1.13.3-43)

**Comment by NPellet** [comment]
Ok, here's an update since v1.13.3-44:

The grid lines are now only one DOM element (a path).
This should save up considerable rendering CPU as it triggers only one layout for the whole grid.

The tradeoff is that you need to call ```axis.setGridLinesStyle()``` after setting the grid line style through the API (not via the constructor, though):

```
  graph.getYAxis().setPrimaryGridColor("#000000")
    .setPrimaryGridWidth(3)
    .setPrimaryGridOpacity(0.9)
    .setPrimaryGridDasharray( "5,5" )
    .setGridLinesStyle();```

**Comment by lpatiny** [comment]
Perfect thanks. We will mainly play with the color for the moment.

**Comment by targos** [comment]
I made the primary grid slightly darker: 
![image](https://cloud.githubusercontent.com/assets/2352663/12387754/079a78b2-bdcf-11e5-9852-149bf65f1d95.png)
