### ISSUE TITLE
Slick grid : allow column with logo associated to an action 

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#768]
The idea would be to have dedicated columns allowing to insert information about the reagents in the rich text editor or to add the molecule in the reaction scheme

Testcase: http://visualizer.epfl.ch/tiny/Sbyrj30JhaAbbuNlchFy ([Original URL](http://visualizer.epfl.ch/c/home/index.html?dataURL=%2Fc%2Fe7ec823f14daf7223e7e77261eeebc76%2Fdata.json&viewURL=%2Fc%2Fe7ec823f14daf7223e7e77261eeebc76%2Fview.json&v=HEAD))

**Comment by stropitek** [comment]
Done. See testcase http://direct.lactame.com/visualizer/src/index.html?config=../testcase/config/default.json&viewURL=../testcase/data/slickActionColumn/view.json&dataURL=../testcase/data/slickActionColumn/data.json
