### ISSUE TITLE
Seems the svg editor use wrong relative links

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#770]
GET http://visualizer.epfl.ch/c/home/lib/svg-edit-2.7/svg-editor.html?extension…76%2Fdata.json&viewURL=%2Fc%2Fe7ec823f14daf7223e7e77261eeebc76%2Fview.json 404 (Object Not Found)(anonymous function) @ init.js:2w @ init.js:1fa.fn.extend.append @ init.js:2(anonymous function) @ init.js:2xa @ init.js:2fa.fn.extend.html @ init.js:2$.extend.init @ view.js:1p.reload @ init.js:20(anonymous function) @ init.js:20f.doClick @ init.js:15(anonymous function) @ init.js:15fa.event.dispatch @ init.js:2b.dispatch @ init.js:10q.handle @ init.js:2
view.js:1 Uncaught TypeError: Cannot set property 'options' of undefined(anonymous function) @ view.js:1fa.event.dispatch @ init.js:2b.dispatch @ init.js:10q.handle @ init.js:2
init.js:2 GET http://visualizer.epfl.ch/c/home/lib/svg-edit-2.7/svg-editor.html?extension…76%2Fdata.json&viewURL=%2Fc%2Fe7ec823f14daf7223e7e77261eeebc76%2Fview.json 404 (Object Not Found)

**Comment by stropitek** [comment]
Is this resolved now?

**Comment by lpatiny** [comment]
Looks much better indeed. If possible would be nice to prevent the double scroll bars

![image](https://cloud.githubusercontent.com/assets/1484241/12886131/8926fdea-ce6b-11e5-833a-177e44786146.png)
