### ISSUE TITLE
rich text editor and input variable

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#771]
It seems that currently the rich text editor store systematically it's content in the view preferences. I have a situation in which I have an input variable that on loading display the value but is directly erased by the default value of the module.

There should be an option to define if the value is saved in the view (default value) or not and if it is not saved in the view nothing should be done on load.

**Comment by targos** [comment]
should be fixed by 57703b21ea814cf1c71105a687d3d151f8b83ae0

**Comment by targos** [comment]
can you try on HEAD and close this if it works ?
