### ISSUE TITLE
Spectra displayer flip axes

### ISSUE THREAD

**Issue by andcastillo** [NPellet/visualizer#773]
The spectra displayer change the setting  for "flip axes" x and y by it self. I could not flip and show the x axe, with the y axe not flipped not showed. 

Testcase: http://visualizer.epfl.ch/tiny/3Wz1Kj4ys2MJETNjHTT4 ([Original URL](http://www.cheminfo.org/static/index.html?dataURL=http%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo%2F38ed886965140cee37a571e6315f2543%2Fdata.json%3Frev%3D6-8e27aa9855f4b6fa460e819de48a3914&viewURL=http%3A%2F%2Fwww.cheminfo.org%2Fclp%2Fc%2F1ddc5b5a03b6cdab9476160c950293c3%2Fview.json&v=HEAD))

**Comment by targos** [comment]
Sorry, I do not understand the issue. Is it the migration that went wrong ?

**Comment by andcastillo** [comment]
MMM. No. It seem was my computer. Restarting the computer solved the problem. The problem was that the settings changed alone.

**Comment by andcastillo** [comment]
It happens again and again. I'll try to describe de problem:
1. I have a NMR spectrum. The spectra displayer should show the spectrum, the x axe scale, tics, and it should be inverted(from right to left).It should not to show the y axe. So, I set those parameters in the options:
![Desired setting](https://cloud.githubusercontent.com/assets/3810292/12753054/4b1f8f6c-c993-11e5-9335-d48c7d42c010.png)

But, after I save the setting, I get this spectrum:
![Spectrum](https://cloud.githubusercontent.com/assets/3810292/12753150/c89b2fe6-c993-11e5-80bc-c54863d0f393.png)
As you can see, the x axe is not inverted and is not displayed. What happen? I go back on the settings and I see this: 
![Spectra displayer settings ](https://cloud.githubusercontent.com/assets/3810292/12753182/f519a322-c993-11e5-91d7-bb839bc1be55.png)

As you can see the settings was restarted magically. I try re-setting and I get this:

![screen shot 2016-02-02 at 9 54 55 am](https://cloud.githubusercontent.com/assets/3810292/12753220/2a1a93e2-c994-11e5-912c-bf5c307abc11.png)

I set the parameters again and I get this:
![wrong again](https://cloud.githubusercontent.com/assets/3810292/12753271/56bebfb8-c994-11e5-8aba-c36e3144feb0.png)

And the setting are again wrong:

![wrong settings](https://cloud.githubusercontent.com/assets/3810292/12753294/7634fb64-c994-11e5-8bb3-3a5ed2675a1a.png)

**Comment by targos** [comment]
I am not able to reproduce this issue.
Does it happen on a specific view ? If yes, please share it.
If the "share view" makes the problem disappear, please take the JSON with "Copy view" and send it to me by email.

**Comment by andcastillo** [comment]
It was on that specific view. Nevertheless, I relate this problem to a kind of memory leak in the gsd library. After I solved it, the problem do disappear.
