### ISSUE TITLE
Onde crash if the object in not of type DataObject

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#777]
https://github.com/NPellet/visualizer/blob/master/src/modules/types/edition/onde/view.js#L123

I think we should add a condition there to check if it can be resurrected

**Comment by targos** [comment]
the value should always be a dataobject at this point. can you share a testcase?

**Comment by lpatiny** [comment]
OK maybe there is a mistake in the script then. You can find a relatively complex view here:

http://visualizer.epfl.ch/tiny/oTo61BTtEapinFYs4GNL

When you click on a property from the "List of properties" an action will be send to the script "We want to add a property" that creates the value and ondeTemplate that will generate the error.
