### ISSUE TITLE
How to create subvariable ?

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#778]
http://visualizer.epfl.ch/tiny/J97eLdej2RwVfZR43uLX

If product is a DataObject and in a code executor I add a bp I would expect that createDataJpath would ensure that the exported value is a DataObject (or corresponding Data kind object) and set correctly the _parent and manager the changevalue trigger. This does not seem the case currently

```
product.bp={
    type:'object',
    value:{low:123},
};

API.createDataJpath('value',product,['bp']);
```

**Comment by targos** [comment]
please try the fix that is on HEAD

**Comment by lpatiny** [comment]
I'm working on the head but if I change the value low / high it seems the value does not change (in-place modification in the onde module and display of that value just under).
Also on the top we see the current product and it seems that the "bp" is not appended in the product.

![image](https://cloud.githubusercontent.com/assets/1484241/12749606/10ca187c-c9b2-11e5-8b52-33264124bbf3.png)

**Comment by targos** [comment]
I can't help you from here, the computer has a too old version of Chrome...
