### ISSUE TITLE
barcode renderer

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#779]
Would be nice to have a renderer for type="barcode" using jsBarcode.

This will also allow to have a barcode in a twig module !

The source of a barcode is either a string or a number and I don't know if we should create a type='barcode' or we should allow an option for number and string renderer

Something like:

{
type:'string',
value:"my barcode',
_options: {
  barcode: {
    width:  2,
    height: 100,
    quite: 10,
    format: "CODE128",
    displayValue: false,
    fontOptions: "",
    font:"monospace",
    textAlign:"center",
    textPadding:0,
    fontSize: 12,
    backgroundColor:"",
    lineColor:"#000"
}
}

**Comment by targos** [comment]
I'm in favor of a barcode renderer. You can always force the renderer in your twig template even if the input is not of `type: 'barcode'`

**Comment by lpatiny** [comment]
OK good point. I forgot this option !
