### ISSUE TITLE
spectradisplayer and input of empty data

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#781]
When there is displayed a spectraDisplayer module with peak picking (Chart input variable) and we clear this variable the spectrum disappear but the labels are still there.

**Comment by lpatiny** [comment]
In fact the labels are never cleared:
Test case: http://visualizer.epfl.ch/tiny/nFspRMBqRZbkPw4AkURQ
Just change the value in the array

**Comment by NPellet** [comment]
Can be a jsGraph issue.

Technically when a serie is removed, the shapes associated to the serie
should ALSO be removed if kill( true ) is used

2016-02-03 10:42 GMT+01:00 lpatiny <notifications@github.com>:

**Comment by lpatiny** [comment]
It is a little bit messy currently ;)

![image](https://cloud.githubusercontent.com/assets/1484241/12787356/62d38c50-ca95-11e5-9d0d-045b3bd2d849.png)
