### ISSUE TITLE
spectraDisplayer : hover peak picking generates an error

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#785]
http://visualizer.epfl.ch/tiny/nFspRMBqRZbkPw4AkURQ

If you go over a label there is an error in the console

**Comment by lpatiny** [comment]
It is a little bit messy currently ;)

![image](https://cloud.githubusercontent.com/assets/1484241/12787356/62d38c50-ca95-11e5-9d0d-045b3bd2d849.png)

**Comment by targos** [comment]
There is no data in your example

**Comment by lpatiny** [comment]
Sorry
http://visualizer.epfl.ch/tiny/Rc8AxT64rLFAnBjhTnIo
