### ISSUE TITLE
spectraDisplayer input spectra object

### ISSUE THREAD

**Issue by andcastillo** [NPellet/visualizer#787]
Would it be possible to include in the list of input objects, the kind of object returned by jcampConverter?
My problems is as follows: I have a list of NMR spectra, some light 1D jcamp and some heavy 2D. I have an spectraDisplayer for 1D and an spectraDisplayer for 2D. I would like to send the elements of the list that was preloaded previously by another function, to the corresponding displayer. I want to go back over previously loaded spectra, but I don't want to parse 20Mb of text each time.  

Is that feasible?

**Comment by targos** [comment]
is it ok for you if I modify the current jcamp input to accept the following ?

```js
{
  type: 'jcamp',
  value: {} // object returned by the jcampconverter
}
```
