### ISSUE TITLE
Upload attachments in couch button

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#789]
Allow any characters but "/" ? What is really not allowed by couch for filenames ?

I had the problem with é è ...

**Comment by targos** [comment]
As far as I know any name can be used but it has to be URL encoded

**Comment by targos** [comment]
What is your problem exactly ? I am able to upload attachments with special characters

**Comment by lpatiny** [comment]
In the current version if you upload a batch of files the one containing non a-zA-Z0-9 are not uploaded.

**Comment by targos** [comment]
This works as expected in the new roc-views button
