### ISSUE TITLE
my.cheminfo.org

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#796]
When I go to this website I can login using google on rest-on-couch.cheminfo.org but when I go back on my.cheminfo.org there are not buttons int he header
![image](https://cloud.githubusercontent.com/assets/1484241/12971616/5ada7ece-d09d-11e5-9b78-29a4c8ab69e8.png)

**Comment by targos** [comment]
we did not release it yet. you need to use HEAD

**Comment by targos** [comment]
We have now a release with roc-views
