### ISSUE TITLE
color syntaxing disappeared

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#797]
On head-min the code executor does not have color syntaxing anmore

![image](https://cloud.githubusercontent.com/assets/1484241/12981830/a2b3efe2-d0e2-11e5-8fc4-5f7522dff5fa.png)

**Comment by stropitek** [comment]
From time to time, when working on my.cheminfo.org, I still have this issue

**Comment by targos** [comment]
that's a bit vague...

**Comment by stropitek** [comment]
Well I haven't investigated why...

**Comment by stropitek** [comment]
![screenshot from 2016-02-17 11-06-08](https://cloud.githubusercontent.com/assets/4118690/13106045/8b3f583c-d566-11e5-9226-0bb4178fa4f6.png)
