### ISSUE TITLE
Spectra displayer and Y serie input

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#798]
http://visualizer.epfl.ch/tiny/s7IveuEMy47L2utdfQSY

When there is a Y serie input the 2 axis seems to be linked and there is no way to invert one axe without inverting the other one

**Comment by targos** [comment]
what do you mean by "invert one axe" ?

**Comment by andcastillo** [comment]
I think this is related to this issue #773. I've closed it twice, but I still getting the problem sometimes.
