### ISSUE TITLE
QRcode different behaviour

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#800]
When changing the value of the QRCode it takes the whole surface of the single value module while if you resize the single value module it takes the expected "1 point size".

Testcase: http://visualizer.epfl.ch/tiny/T9Ulx05fnj2W4lWNAZdu

**Comment by stropitek** [comment]
There is no option in this library to set the point size. You can only set the width and height of the final qrcode. I suggest that the image fills the div in which it is displayed unless width and height are specified in the options then it generates an image of that size.

**Comment by lpatiny** [comment]
The problem is not there. The problem is that the barcode change of size if you take the example, go int he preferences of the single value module and validate.

**Comment by stropitek** [comment]
This was the behaviour that I tried to have, but the automatic width and height does not work for some reason. It seems that the div that the renderer receives when rendering in a single value module after resize is always 100x100. I have no clue why, the size of the div is correct when ```tyerenderer.render``` is called but as when the div is passed to ```toscreen``` its size has changed to 100x100....

**Comment by targos** [comment]
resizing the module is done during development. It is not very critical that some things are "broken" when we do it

**Comment by stropitek** [comment]
In this case it also didn't work when re-initializing the module.
Fix by setting default width and height instead
