### ISSUE TITLE
my.cheminfo.org layout

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#803]
Seems there is a CSS problem on the new site.
The text of the head of boxes is quite big
![image](https://cloud.githubusercontent.com/assets/1484241/13049561/126bd558-d3ee-11e5-87ed-bbb180139ea2.png)
Same is true for the header of table in preferences
![image](https://cloud.githubusercontent.com/assets/1484241/13049573/2c7b0072-d3ee-11e5-9a95-45e5e52a1a1c.png)

**Comment by targos** [comment]
I don't understand what's causing this. The CSS is correctly loaded

**Comment by lpatiny** [comment]
The difference seems that the font-size is medium in the new layout
![image](https://cloud.githubusercontent.com/assets/1484241/13056465/c4da9ffe-d415-11e5-8a97-1aca314c4fdd.png)

And before it was not specified (and therefore 11px I think)
![image](https://cloud.githubusercontent.com/assets/1484241/13056474/d4e24d2a-d415-11e5-8856-c4a976d58858.png)

But what means this "Attributes style" ?

**Comment by stropitek** [comment]
```<!DOCTYPE html>``` was missing

**Comment by lpatiny** [comment]
I would never find this !!!

**Comment by stropitek** [comment]
It was a lucky guess!
