### ISSUE TITLE
www.cheminfo.org tries to load CLP using http and not https

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#805]
![image](https://cloud.githubusercontent.com/assets/1484241/13049813/bd585170-d3ef-11e5-9719-c47f1a353737.png)

http://www.cheminfo.org/Chemistry/Cheminformatics/Reagents_calculator/index.html?viewURL=http%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo%2Fe7ec823f14daf7223e7e77261eeebc76%2Fview.json%3Frev%3D202-76b7c15bcf599a589b3ce6c68bc4290b&dataURL=http%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo%2Fe7ec823f14daf7223e7e77261eeebc76%2Fdata.json%3Frev%3D202-76b7c15bcf599a589b3ce6c68bc4290b

**Comment by targos** [comment]
this is expected. I put clp offline so we don't store view in the old database by mistake

**Comment by targos** [comment]
The error will disappear when the flavor is built with the new template
