### ISSUE TITLE
view manager: error loading flavor 'test'

### ISSUE THREAD

**Issue by stropitek** [NPellet/visualizer#814]
I get ```cannot read 'length' of undefined``` when trying to load the ```test``` flavor with ```admin@cheminfo.org```

![image](https://cloud.githubusercontent.com/assets/4118690/13289442/59416730-db10-11e5-9934-65523cb21998.png)

**Comment by targos** [comment]
should be fixed by 1784286e60a827e5cdb77044e10e7f7d7eb7f427
