### ISSUE TITLE
Problem loading lodash

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#816]
When trying to load locally:

http://localhost:63342/visualizer/src/index.html

There is a file that is not found because in looks in the folder "dist" and it is directly in the lodash folder.

![image](https://cloud.githubusercontent.com/assets/1484241/13312459/05454be2-db97-11e5-9ef1-d7be08ef197d.png)

**Comment by targos** [comment]
run `npm install` (not update) to retrieve bower components (the files in lodash were moved in latest version)
