### ISSUE TITLE
slick grid crash when on a hidden layer

### ISSUE THREAD

**Issue by targos** [NPellet/visualizer#817]
If slick grid receives a new variable when hidden from the current layer, I get the following error:

![image](https://cloud.githubusercontent.com/assets/2352663/13314284/a1affb32-dba4-11e5-9da2-05d5004e1291.png)

**Comment by stropitek** [comment]
I wasn't able to reproduce
https://visualizer.epfl.ch/tiny/JVOfslAq6xes5kKmplsa

**Comment by targos** [comment]
ok, closing then. we can reopen if necessary
