### ISSUE TITLE
Allow edition of other types in slickgrid as text

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#821]
When you have a molecular formula it is rendered correctly in a slickgrid. It would be nice that if you say it is a DataString editor, it will be edited as a string.

**Comment by stropitek** [comment]
I've made some improvements:
- the from type editor is smarter and recognizes types like ```mf``` as needing a text editor (uses ```structures.js```
- You can force the type of a column. This force the type when editing value (new or existing)
- Simpler editor options: 3 base type editors (`string`, `number`, `boolean`) that will handle both typed and not typed values
