### ISSUE TITLE
type, url requests and whithCredentials

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#822]
6 fails / 3 success

https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F13a5028017f3fdcd3d5c0ce3215e8b9b%2Fview.json

**Comment by targos** [comment]
fixed by e1850ffa59301c4f6c2f33d85fb821f6d3043c96 and 20ebb4114dcbbf062c0bfc67ee050509c1393b74
