### ISSUE TITLE
Value display : allow to force the type renderer

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#825]
Like in slick grid it would be nice to be able to force which type renderer should be used.

This will allow to have this option in:

- display value
- slick grid
- twig renderer

In most of the case this will prevent us to have the requirement of specify type:'mf' or 'mol2d' for example which will be much cleaner to save the data in a NoSQL database.

**Comment by stropitek** [comment]
Fixed in 59b03b93ed364ad72e28a32042f049bdf693ae5b
