### ISSUE TITLE
Forcing type renderer

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#826]
When forcing to a specific type renderer we could deal with the following situation when we have an object:

{value:"CCCCC"}

if we "force type" to smiles it should be rendered like if it was:
{type:"smiles", value:"CCCCC"}

So in fact the same as if it was "CCCCC" and we force it to "smiles".

Same is true for:
{value:"gFp@DiTt@@@", coordinates:"!B`BHX`Bb@JH_P"} and forced to oclID should be rendered as

{type:"oclID", value:"gFp@DiTt@@@", coordinates:"!B`BHX`Bb@JH_P"}

**Comment by stropitek** [comment]
Fixed in fd71b385e8d04e1f34d1d0683f66e45ed4be46b4
