### ISSUE TITLE
API.cache is not cleared when changing view

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#830]

**Comment by targos** [comment]
It is the same with the data.
Do we want to change this behavior globally ?
- if we load a new view.json, delete the data and the cache
- if we load a new data.json, delete the view and the cache

**Comment by targos** [comment]
It would be complicated to delete the view if a data.json is loaded.
I propose to only do 1.

**Comment by stropitek** [comment]
Yes let's do only 1.
