### ISSUE TITLE
Web service search and forms

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#840]
Currently the button is include inside the table and this gives strange effect when the label of the button is large.
I think it should be moved just after the table (and before the feedback).

**Comment by stropitek** [comment]
An example?

**Comment by lpatiny** [comment]
{
  "version": "2.48.0",
  "grid": {
    "layers": {
      "Default layer": {
        "name": "Default layer"
      }
    },
    "xWidth": 10,
    "yHeight": 10
  },
  "modules": [
    {
      "url": "modules/types/server_interaction/webservice_search/",
      "configuration": {
        "sections": {
          "postvariables": [
            {
              "sections": {},
              "groups": {
                "postvariables": [
                  [
                    {
                      "destination": "data",
                      "filter": "none"
                    }
                  ]
                ]
              }
            }
          ]
        },
        "groups": {
          "group": [
            {
              "url": [
                null
              ],
              "method": [
                "POST"
              ],
              "dataType": [
                "form"
              ],
              "withCredentials": [
                []
              ],
              "showStatus": [
                []
              ],
              "button": [
                [
                  "button"
                ]
              ],
              "buttonlabel": [
                "My long button text that is really to long"
              ],
              "buttonlabel_exec": [
                "Exec"
              ],
              "onloadsearch": [
                []
              ],
              "debounce": [
                0
              ],
              "resultfilter": [
                "return data;"
              ],
              "askConfirm": [
                []
              ],
              "confirmText": [
                "Are you sure?"
              ]
            }
          ],
          "headers": [
            [
              {}
            ]
          ],
          "searchparams": [
            [
              {
                "name": "ABC",
                "destination": "url",
                "label": "ABC",
                "fieldtype": "text"
              }
            ]
          ]
        }
      },
      "layers": {
        "Default layer": {
          "position": {
            "left": 32,
            "top": 9
          },
          "size": {
            "width": 51,
            "height": 23
          },
          "zIndex": 0,
          "display": true,
          "title": "",
          "bgColor": [
            255,
            255,
            255,
            0
          ],
          "wrapper": true,
          "created": true,
          "name": "Default layer"
        }
      },
      "id": 1,
      "vars_in": [
        {}
      ],
      "actions_in": [
        {}
      ],
      "title": "",
      "vars_out": [
        {
          "jpath": []
        }
      ],
      "actions_out": [
        {
          "jpath": []
        }
      ]
    }
  ],
  "variables": [],
  "aliases": [],
  "pouchvariables": [],
  "configuration": {
    "title": "No title"
  }
}
