### ISSUE TITLE
jsGraph and time series

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#841]
After importing a XY array of a time serie, when I say for the X axis:

TimeStampToTime

I get an error:

Error loading the graph TypeError: this.setMinMaxFlipped is not a function(…)

**Comment by targos** [comment]
Can you provide a testcase ?
/cc @NPellet

**Comment by NPellet** [comment]
Ah yeah ok it came in the latest version

**Comment by targos** [comment]
I think it's fixed with v1.13.3-71
