### ISSUE TITLE
twig template input variable

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#849]
If the twig template is defined from a variable in it will still go in the preferences of the twig module.

This does not seem logical

**Comment by targos** [comment]
I did it like that with the idea that you use an input variable to develop the template and then remove the code editor while keeping the code in the preferences.

**Comment by targos** [comment]
But I will change it, it's not difficult to copy-paste if needed

**Comment by targos** [comment]
There is another module that works like that: code editor. Do we want to do the same to it ?

**Comment by lpatiny** [comment]
I was not aware of this feature that the code is also in the preferences of the module. The consequence is that we have 2 times the template in the view then because I tend to have an admin layer in order to create / debug the template. We should decide what is the expected behaviour.

**Comment by lpatiny** [comment]
And yes if it is changed the other module should have the same behaviour.
