### ISSUE TITLE
Openchemlib gives an error if you add implicit hydrogens

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#852]
Testcase: https://visualizer.epfl.ch/tiny/XlKMVwqy8T66V18IqgMi ([Original URL](https://www.lactame.com/visualizer/HEAD/))

**Comment by targos** [comment]
sometimes you cannot use OCL core to generate the SVG. You have to include openchemlib-viewer.js

**Comment by lpatiny** [comment]
Sometimes seems a little bit annoying. We could try to check if something could be done ? Otherwise toSVG should be removed from the core and stay only the full library I think.

**Comment by targos** [comment]
This has been fixed in [OCL@4.2.1](https://github.com/cheminfo/openchemlib-js/releases/tag/v4.2.1)
