### ISSUE TITLE
Rendering array of type html in slick grid

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#853]
[[type:"html", value:"<b>test</b>"] is not rendered in a slick grid correctly.

However if you force the type from the preferences it works correctly.

**Comment by stropitek** [comment]
Cannot reproduce
Testcase: https://visualizer.epfl.ch/tiny/SHsHS2RlHaPqtFY0Fwjo ([Original URL](https://www.lactame.com/visualizer/latest/))

**Comment by lpatiny** [comment]
Me neither :( sorry.
