### ISSUE TITLE
https migration of wikipedia on cheminfo.org

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#856]
https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F037628b00519031c1df72b6eec3e721e%2Fview.json

After migration (replace http to https) the page crash. Would it be related to a change in the version of openchemlib ?

**Comment by targos** [comment]
fixed
