### ISSUE TITLE
Update templates in Periodic Table demo

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#857]
https://my.cheminfo.org/?dataURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F322d373f937cb95a6706334d60054340%2Fdata.json&viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F322d373f937cb95a6706334d60054340%2Fview.json

Seems the list of templates disappeared and it is now necessary to develop 2 templaces I think.

**Comment by stropitek** [comment]
Fixed
