### ISSUE TITLE
Add an object renderer

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#858]
It would be nice to have an object renderer.
The first renderer could be
toJSON:true
That would just convert the object to json

https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F8ca344af98e453e75650f2dc932914d1%2Fview.json

**Comment by stropitek** [comment]
We already have a renderer for objects with the twig option

**Comment by targos** [comment]
should we put a default indentation for JSON ?

**Comment by stropitek** [comment]
Probably we need the option. Don't know if default should be with or without indentation.
