### ISSUE TITLE
No module list on flavor 1024

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#864]
http://www.cheminfo.org/flavor/1024/Basic/1._Simple_addition.html?viewURL=http://couch.cheminfo.org/cheminfo/16e029673e68d05b6df709e2970dbdc5/view.json?rev=3-51197412712317724fcc934cb1ab046e&v=v2.22.0

I would like make a demonstration where I can add a module but nothing is available. I don't know if this is the expected behaviour but it is problematic for me.

**Comment by stropitek** [comment]
You are using an old build of the view.

The latest build corresponding to this view is : http://www.cheminfo.org/flavor/1024/Basic/1._Simple_addition/index.html?viewURL=https%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo-public%2F16e029673e68d05b6df709e2970dbdc5%2Fview.json%3Frev%3D1-c2b925a134a9b05c849177f6bb2aeafa
