### ISSUE TITLE
Improve matrix module to output value

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#871]
Currently the matrix allows as output variable the current row, current column and the value of the current pixel.
Some improvement could be done:
* allow as input variable just a 2D array
* allow as output variable:
  * a 1D array containing the values of the click / hover current row
  * a 1D array containing the values of the click / hover current column
  * an object containing : [row, column, z] (z=value of the pixel) (don't know if we have a better format for this ?)

**Comment by targos** [comment]
I think I'll go for `{ row, column, value }`
