### ISSUE TITLE
Not able to attach a document to a view

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#872]
Don't know what is wrong and what is the easiest way to attach a JSON

CouchAttachments = src/util/couchdbAttachments

var ca = new CouchAttachments();
ca.upload([{
  name: 'matrix.json',
  contentType: 'application/json',
  data: JSON.stringify({a:1})
}]).then(function(result) {
    console.log(result);
});

https://visualizer.epfl.ch/tiny/Qc5ZWoeDcfcUeZIdd8DH

**Comment by stropitek** [comment]
the `upload` methods only allows you to send one file at a time. Your example will work if you pass just the object not an array.

To pass multiple uploads use the `inlineUploads` method
