### ISSUE TITLE
api.setVariable crash if getjPath is undefined

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#877]
api.js:169 Uncaught TypeError: Cannot read property 'concat' of undefined

![image](https://cloud.githubusercontent.com/assets/1484241/15173385/14665480-175c-11e6-969d-e08d80b8ae4f.png)

**Comment by targos** [comment]
I'm currently rewriting this code but can you post a testcase ?

**Comment by lpatiny** [comment]
You may check this view. When you click on a row it crash
https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F56a775cce8f11984f97b5ec22089ddae%2Fview.json

**Comment by targos** [comment]
looks like a bug with this new "In view data" rel. cc @stropitek
