### ISSUE TITLE
_.pluck is not a function

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#879]
Seems there are some problems trying the use the pdbexplorer with the last version of the visualizer:

CodeExecutor28@0:57 Uncaught TypeError: _.pluck is not a function

It is not the only view that has this kind of problem that seems to be related to unserscore

**Comment by stropitek** [comment]
Yes lodash has removed `pluck` from their api. You should use `map` instead. Those views need to be migrated manually.
