### ISSUE TITLE
Slick problem in malaria view

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#881]
When trying to migrate the view I have the following error

www.lactame.com/visualizer/latest/modules/types/edition/slick_grid/view.js:1 Uncaught TypeError: (this.module.getConfiguration(...) || []).filter is not a function
www.lactame.com/visualizer/latest/init.js:31 Alias debouncing not defined 

I saved in as test-malaria in the flavor test:

https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2Fd53bdd6977d35b826aebb73aae73bd43%2Fview.json

[view.json.zip](https://github.com/NPellet/visualizer/files/266607/view.json.zip)

**Comment by stropitek** [comment]
I don't know where the problem comes from but I've added a migration script to handle it
