### ISSUE TITLE
In slick grid variable out: filtered

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#882]
Would be nice to have in slick grid a variable out containing the currently "filtered lines. If you add in the search boxes a query this would allow to be able from another module to easily export this list.

**Comment by targos** [comment]
If we add this, we must be very careful. The elements in the filtered array will lose their original parent (the unfiltered one) and triggerChange will probably have unexpected results

**Comment by lpatiny** [comment]
How you do with you quick array filter module ? We also loose the reference to the original data ?

**Comment by targos** [comment]
yes we do but we usually don't use the original array

**Comment by targos** [comment]
use smart filter
