### ISSUE TITLE
couchDB button and revision

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#883]
It would be nice if the revision part of the couchDB view manager button could be developed. I too often do mistaes ;)

**Comment by targos** [comment]
That means adding support for revisions in rest-on-couch. Then there is the question of permissions.
 Do we use the permissions of the latest revision or of the requested one?

**Comment by lpatiny** [comment]
I guess it is logical to keep the permission of the revision even if sudently you may not have access to the revision anymore ... What you would do ?

**Comment by targos** [comment]
Revisions are now loadable. 

@lpatiny @stropitek @andcastillo please test the functionality on HEAD and provide feedback here.
