### ISSUE TITLE
Onde form and output result

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#885]
I have some preferences stored in local storage that are common to many views. It is saved as a big JSON.

I load those preferences as input variable of an onde module in which the Schema are defined in the preferences of the module.
What I need is:
1. that any changed are saved in localStorage (based on a trigger change and therefore in place modification)
2. that the onde module "filters" the input variable so that I only have the fields defined in the Schema (which is the default behaviour of a output variable).

Would it be possible in the preferences to have for "Output result" both New object and Modified input object.

This would really solve my problem because currently my function received a lot of options that are saved in the localStorage preferences but that the user even does not see so it not aware off. And I don't see how to solve tis ...

**Comment by targos** [comment]
try with a3dcce8bfbd4364ac3b2f749e9d9579fbf214b40
