### ISSUE TITLE
No way to attach SDF file to a view

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#887]
Trying to upload a SDF (via the view manager button interface)  I get the message:

![image](https://cloud.githubusercontent.com/assets/1484241/15461050/9649f650-20b7-11e6-932f-1c1996ed6a6e.png)

Should mimetype determination be a common method in the whole visualizer ? Would be nice to have the mimetypes:
* mol	chemical/x-mdl-molfile	MDL Molfile
* jdx, dx	chemical/x-jcamp-dx	JCAMP Spectroscopic Data Exchange Format
* sdf	chemical/x-mdl-sdfile	Structure-Data File
* cdx	chemical/x-cdx	ChemDraw eXchange file
* c3d	chemical/x-chem3d	Chem3D Format	
* chm	chemical/x-chemdraw	ChemDraw file	
* cif	chemical/x-cif	Crystallographic Information File, Crystallographic Information Framework

**Comment by stropitek** [comment]
Cannot reproduce with an sdf using latest release. The upload succeeds with mime type `application/octet-stream`. There is already a file (`src/utils/mimeTypes.js`) for custom mime types. Ideally the mime types should be added to [mime-db](https://github.com/jshttp/mime-db)

**Comment by lpatiny** [comment]
Daniel you could make a pull request with the addition of the proposed format ?
The reference would be : https://en.wikipedia.org/wiki/Chemical_file_format

Maybe you could improve mimeTypes.js so that we can add the next extensions / mimetype in the same format as in mime-db as long as they don't add our requests. What do you think ?

**Comment by stropitek** [comment]
ok will do. The visualizer library uses the same api as the original library, so it will be a simple change if we don't need our library anymore. I don't see the advantage of using the mime-db format for our custom extensions. We only need to make it simple to add them.

**Comment by stropitek** [comment]
Have you ever considered registering those type to IANA? This would be the best (but not simplest) way to add them to mime-db (iana types are automatically fetched and added there)
http://www.iana.org/form/media-types
