### ISSUE TITLE
Code executor deboucing

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#896]
Would it be possible in a code executor to debounce ?

I have a lot of time the variable in that changes and i would like to delay the execution of 100 ms as long as the variable in changes.

Is it possible to achieve this currently ?

**Comment by stropitek** [comment]
```js
var debounced = API.cache('debounced');

if(!debounced) {
    debounced = _.debounce(process, 1000);
    API.cache('debounced', debounced);
}

debounced();

function process() {
    console.log('xxx')
    
    API.cache('debounced', undefined);
}
```

**Comment by lpatiny** [comment]
Thanks works perfectly !
