### ISSUE TITLE
program freezed

### ISSUE THREAD

**Issue by visualizer-feedback** [NPellet/visualizer#899]
program freezed and options buttons disapperead. 
reloading is not effective.

Testcase: http://visualizer.epfl.ch/tiny/Ak6wnz04OwGQKEBk0wdL ([Original URL](http://www.lactame.com/visualizer/v2.9.9/index.html?views=https%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FP4rS24iSM8%2Ftest%40patiny.com%2FTeaching%2FBioorientedChemistry%2FStudents%2F2015-2016SV%2Feliane.roosli%40epfl.ch%2FMyProject%2F.views&results=https%3A%2F%2Fscript.epfl.ch%2Fscript%2FRevision%2FmdaKRDPfv2%2Ftest%40patiny.com%2FTeaching%2FBioorientedChemistry%2FStudents%2F2015-2016SV%2Feliane.roosli%40epfl.ch%2FMyProject%2F.results&viewBranch=Master&resultBranch=Master&config=https%3A%2F%2Fscript.epfl.ch%2Fconfigs%2Fhead.json))

**Comment by targos** [comment]
You are using a too old version of the visualizer
