### ISSUE TITLE
NMR simulation view

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#905]
Please could you have a look at the view

https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F4b7669c5ec0a15e6fb3994f53b950277%2Fview.json

that does not seem to work

**Comment by targos** [comment]
fixed. there was a jpath set as output of the spin system module (different than "element")
