### ISSUE TITLE
spectra displayer does not allow zoom anymore (head)

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#907]
Seems I could not zoom on this view if it is on the head

https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F4b7669c5ec0a15e6fb3994f53b950277%2Fview.json&v=HEAD

**Comment by targos** [comment]
there is no issue with the spectra displayer, the lactame build has a problem
