### ISSUE TITLE
pasting png file and clipboard content

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#913]
I did a "private" view (in Test flavor) : Test png:

 https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2Fb1d9fbc6670f5236f9ff2a00d0386f34%2Fview.json

In the module drag / drop there is a "Read type" that may be Array buffer. Is this expected to work and how ?

Would it be possible to use the PNGreader library in this code to check the png content of the image.

If I have many "flavor" in the clipboard I would have a pop-up window ?

Still looking for the meta data of the image ... It "should" be there somewhere ... Maybe there is a difference from chemdraw when you save as png or if you copy / paste the structure directly from the clipboard ...

![image](https://cloud.githubusercontent.com/assets/1484241/16150717/160a5eda-3499-11e6-9991-bf12b870ccfe.png)

**Comment by targos** [comment]
ArrayBuffer works only if you export the parent object (not content) otherwise it is converted to a DataObject

**Comment by lpatiny** [comment]
Apparently even if you clipboard contains many flavor of the data it seems that the browser will filter out only the one that can be paste.
