### ISSUE TITLE
slickgrid "Enable search header" does not working correctly

### ISSUE THREAD

**Issue by David-Turbert** [NPellet/visualizer#924]
With huge data more than 50k rows the functionnality "search header" does not work. When I search something in a column I have nothing displayed.

**Comment by targos** [comment]
@stropitek

**Comment by stropitek** [comment]
any error in the console?
What are you searching? text?

**Comment by David-Turbert** [comment]
any error, I search text

**Comment by stropitek** [comment]
should be fixed by fa0616a78d53d6c3982d319319ee7d215b92a9fd
