### ISSUE TITLE
Customisation of highlight in jsgraph

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#926]
Customisation is possible using the following approach

```
SerieLine.prototype.setLineColor = function( color, selectionType, applyToSelected );
SerieLine.prototype.setLineWidth = function( width, selectionType, applyToSelected );
SerieLine.prototype.setLineStyle = function( number, selectionType, applyToSelected );
```

**Comment by targos** [comment]
This is already in use in the spectra_displayer. Are you asking to add user-defined options ?

**Comment by NPellet** [comment]
The third parameters (bool) allows the serie to take the same style when
its style is set to "selected" (the default style name when the serie gets
selected)

2016-06-29 10:52 GMT+02:00 Michaël Zasso <notifications@github.com>:

**Comment by lpatiny** [comment]
This is mainly to have a trace of this possibility ! I don't think we need it today but Norman example of jsNMR for the selected spectrum is very convincing.
