### ISSUE TITLE
Add action to button, enable / disable

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#927]
Would be nice to have 2 actions in the "button" module.

- disable
- enable

Disabling the button would remove the "hand" and allow as parameter a css of a rectangle that would be put in front of the button.
By default it would be 80% white (20% transparent) so that we can see the button but it really looks disabled.
We could decide then based on CSS that in fact we want that it completely disappear.

**Comment by stropitek** [comment]
ebee8fc76a28774c05e31bc914370bdb19b1e4bc
