### ISSUE TITLE
Leaflet map

### ISSUE THREAD

**Issue by andcastillo** [NPellet/visualizer#937]
It seems that the library has a memory leak problem. Is it possible to update the module?
[Test case](https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F153ae69accee9817aaa3b87fcb20f138%2Fview.json)

**Comment by targos** [comment]
I updated the library but the memory leak was in another component (the visualizer highlight repository). It is fixed now.
