### ISSUE TITLE
jsGraph shapes peakInterval and peakInterval2

### ISSUE THREAD

**Issue by NPellet** [NPellet/visualizer#938]
Hey @targos, @andcastillo,

Can you guys tell me if those two shapes are in use anywhere ? If they are not I think I will archive them.

**Comment by targos** [comment]
I don't think I have ever used them anywhere. There is no occurrence in the visualizer.

**Comment by targos** [comment]
cc @lpatiny @stropitek

**Comment by lpatiny** [comment]
I don't think it is in used on my side. @andcastillo could you confirm on your side ?

**Comment by stropitek** [comment]
I've never used it myself

**Comment by NPellet** [comment]
Ok thank you
