### ISSUE TITLE
Leaflet missing images

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#939]
[Tête de Chalin.gpx.tar.gz](https://github.com/NPellet/visualizer/files/407435/Tete.de.Chalin.gpx.tar.gz)

When dropping the attached file on:

http://www.cheminfo.org/Demo/Maps_-_Trace_viewer/index.html?v=HEAD&viewURL=https%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo-public%2F7c676b4e77fddf06bcfdf5213b5bcd67%2Fview.json%3Frev%3D1-95e2806f85459c56abc3031990d7cd57

There are some missing images

https://www.lactame.com/visualizer/v2.22.0/components/leaflet-omnivore/images/marker-shadow.png

https://www.lactame.com/visualizer/v2.22.0/components/leaflet-omnivore/images/marker-icon-2x.png

**Comment by targos** [comment]
Fixed with leaflet update
