### ISSUE TITLE
Code executor and change button name while executing

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#942]
Would be nice to have 2 labels for the button like "Execute" / "Executing". The button could also be disabled once it is being executing.

Currently with async process it is too easy (and annoying) to click twice on the button(like image analysis or ROC record retrieval)

**Comment by targos** [comment]
What if you forget to resolve the promise / call done ?

**Comment by lpatiny** [comment]
Which may be most quite often at the beginning ... I would propose that the way to reset it is to open / save the preferences

**Comment by targos** [comment]
What about script executions from external events like input variable or action ?
Should it also block the buttons ?
What about CTRL+Enter ?

**Comment by lpatiny** [comment]
I would say that it should indeed change the button status as well so that we know it is running. Would be nice if the button has time to change even if it is a sync script but this would require a setImmediate ?

Nothing against CTRL+Enter or even SHIFT+Enter
