### ISSUE TITLE
Code executor button size

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#947]
The buttons take much more place than before and screw up some existing views because we have now 2 lines.

https://github.com/NPellet/visualizer/blob/master/src/modules/types/client_interaction/code_executor/view.js#L54-L72

The reason seems that forms/button add some span that did not exists before
```
<button type="button" class="form-button Grey" data-id="4" id="button-4">
<span></span>
<span>Next Step</span>
</button>
```
Removing the span would be ok

```
<button type="button" class="form-button Grey" data-id="4" id="button-4">
Next Step
</button>
```
(actually the button would be slightly smaller)

Any reason from those spans ?

**Comment by targos** [comment]
fixed in 70398ce9350b7c24901bedd5e6171a3bd208f1cf
