### ISSUE TITLE
Edit/Display module not displaying

### ISSUE THREAD

**Issue by maasencioh** [NPellet/visualizer#955]
When you try to create it just don't display anithing, so if it's not intended to work shouldn't even be the option to create it

**Comment by stropitek** [comment]
@targos @lpatiny Do we want to maintain this module? I have never used it. It's seems to be a mix of the onde and twig modules

**Comment by lpatiny** [comment]
It was never used seems to me and could be deleted except if there is interesting code. @targos should decide (seems he started it)

**Comment by maasencioh** [comment]
closed with 54818eb

**Comment by targos** [comment]
actually it's closed by https://github.com/NPellet/visualizer/commit/0dbbc4a7e483a461c67b59868dcc3fabd74e0b56

**Comment by targos** [comment]
The module is still here, but hidden
