### ISSUE TITLE
change slick grid to prevent error with undefined ?

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#962]
![image](https://cloud.githubusercontent.com/assets/1484241/18505360/260427ee-7a67-11e6-9a06-18818eca3aeb.png)

**Comment by stropitek** [comment]
I could change the undefined value in the array to be an empty object. But I think the user needs to know about it (notification) since this is likely an error from the developer of the view.

**Comment by targos** [comment]
I'm with Daniel here. If there are undefined values in the array, it must be an error from the developer. The message in the console should be enough to debug it.
