### ISSUE TITLE
twig input variable stay type / url

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#963]
If a input variable in the twig module is of type / url, the corresponding value is not send to the twig renderer but only the 'type / url'

This means if we load the data dynamically we can not render the value in a twig renderer. I think this should be fixed

**Comment by targos** [comment]
this looks more like a bug to me

**Comment by stropitek** [comment]
fixed by 57f0ce9857f9daaca742dd3734375cfe605f25b8
