### ISSUE TITLE
Be able to display easily a 'processing' bar

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#965]
The problem is with retrieval jcamp of large NMR 2D. You never know if it is still processing or if it crashed and we have no visual feedback.

But in this specific case we have 2 parts
* retrieval of the spectrum 
* jcamp converter and contour line generation

How it would be possible that if there is a out of memory error this appears as a feedback to the user ? (ok would only be in firefox because chrome would crash I think)

**Comment by stropitek** [comment]
Can this type of error be caught? if yes we can show feedback with a failure notification. @lpatiny you mention a processing bar in the title, can you be more specific?

**Comment by lpatiny** [comment]
Actually I'm missing some ideas. The problem is that currently when we retrieve a big file with Ajax there is nowhere an indication that something is going on...
There is the font-awesome animate font that looks quite cool to show that something is happening.
Could we do that when there is an ajax call there is always a visual feedback somewhere. Any proposal where we could put something ?

**Comment by stropitek** [comment]
I think UI needs something new in this case. Not the blocking type of feedback of API.loading. Rather a non-blocking notification with an animated icon that goes away when the request is finished and successful and stays and gets updated with the error if the request failed
