### ISSUE TITLE
Position of the menu in "view manager"

### ISSUE THREAD

**Issue by andcastillo** [NPellet/visualizer#967]
I have problems to select elements in the view manager menu, because at 100% zoom, the menu appears above the project list. Why this happens?
Zoom 100%
![screen shot 2016-09-28 at 8 30 30 am](https://cloud.githubusercontent.com/assets/3810292/18915307/318abdea-8556-11e6-9355-7d836fe21a0e.png)
Zoom 65%
![screen shot 2016-09-28 at 8 30 43 am](https://cloud.githubusercontent.com/assets/3810292/18915310/32b7d2d4-8556-11e6-823d-70c1f86de586.png)

**Comment by targos** [comment]
It may happen if the window is too small. What elements do you have trouble to select ?

**Comment by andcastillo** [comment]
Revisions. I need the list as long as possible because it is not scrollable.

**Comment by lpatiny** [comment]
Is there anyway to get the date of the revision ? It would useful for some views where we have several hundreds of resions ...

**Comment by targos** [comment]
No way to get the date

**Comment by targos** [comment]
I mean there is a way but it would need 1 request for each revision. Do you want that ?

**Comment by stropitek** [comment]
A details button like in grm would be handy

**Comment by targos** [comment]
@andcastillo I made some changes. Can you try on HEAD ?

**Comment by targos** [comment]
@lpatiny I added a tooltip that displays the date when you hover the revision ID

**Comment by andcastillo** [comment]
Looks much better. And the "revisions" changes helps a lot.
