### ISSUE TITLE
Bug in the last release in JSME

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#969]
The last release of the visualizer and the current head does not have inplace modification. It seems like there is a kind of infinite loop I don't know exactly what is happening.

We can try in this view but just adding a code editor with the molfile shows that this molfile never change.

https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F0e019bb4d797395213d22aca403d2c93%2Fview.json&v=HEAD

@targos if you could have a look at this tomorrow and if it is not on our side make a revert (take care seems the veirsion before was also buggy)

https://github.com/NPellet/visualizer/commit/e2834afc6b453d8d9c60aa411562770a4565b6c2

**Comment by targos** [comment]
This is a bug in JSME. Has nothing to do with inplace modification. See https://github.com/cheminfo/jsme/issues/8

**Comment by targos** [comment]
Reverted the update in `v2.67.1`
