### ISSUE TITLE
pan zoom on 2 layers fail to zoom in both layers ?

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#971]
https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F687239c2ef25f248d44ee041381a4423%2Fview.json

Click on an image, on the first layer it does not zoo, on the second layer it zoom correctly with the mouse wheel

**Comment by stropitek** [comment]
not a bug
