### ISSUE TITLE
Incompatibility with Safari 10.0

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#974]
The view 

http://www.cheminfo.org/flavor/structuralAnalysis/Mass/Exercises/Electronic_Impact/index.html?viewURL=https%3A%2F%2Fcouch.cheminfo.org%2Fcheminfo-public%2Fbd334bf1e195901c08390405967453bc%2Fview.json%3Frev%3D35-9e4d237a1abc42159e0054749b953241

Has a problem apparently

![image](https://cloud.githubusercontent.com/assets/1484241/19490982/fa82be6a-9536-11e6-9638-505ab5d3ee8f.png)

**Comment by targos** [comment]
What's the value of the Access-Control-Allow-Credentials header?

**Comment by lpatiny** [comment]
OK it appears that on this computer I was 'tuning' the dns and this was the reason. sorry for this !

However the view does not work on Safari 9.0 and even if it is very quiet the reason is that I was using arrow functions ... I'm take bad habits ;)

@targos is there some back rewritting with the last version of the visualizer ? (seems not)

Seems with Safari 9.0 I also have those errors loading an empty page:

![image](https://cloud.githubusercontent.com/assets/1484241/19561351/abab5c40-96d8-11e6-869c-1f023bfb51e8.png)

**Comment by targos** [comment]
with the next release of the visualizer, arrow functions in code executor will be babelized along with any other ES6+ stuff.
What is "back rewriting" ?

**Comment by lpatiny** [comment]
It is your babelizing stuff ;) 

In safari 9 on head-min it works perfectly !!!

**Comment by targos** [comment]
The "official" and more general way to say it (babelize) is "transpile"
