### ISSUE TITLE
Renderer bug from 2.61.0 to 2.63.1

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#975]
The rendering of the molecules where broken between those 2 versions for the view

https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F7cead2ae3da71090cb17baa3856ea38b%2Fview.json

It could be due to the renderer of a data object ?

**Comment by targos** [comment]
The only relevant commit that I see is an update of openchemlib. Trying to revert it now...

**Comment by targos** [comment]
Confirmed the regression happens with https://github.com/NPellet/visualizer/commit/471b86df24d03d11bda1349c75823c088c8e9e55

**Comment by targos** [comment]
it was already there in OCL 4.3.1

**Comment by targos** [comment]
I don't know what it can be. There were only updates to the java code

**Comment by lpatiny** [comment]
The molfile is strange because there are no coordinates. I will check if it can be this.

**Comment by targos** [comment]
I'll try to update OCL to the latest version
