### ISSUE TITLE
type renderer for array ?

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#976]
Would be nice to have a type renderer for array that does nothing (well the same as today)

But that allows an option 'length' that if present returns the length of the array

Currently we often need to create a code executor just to get the length of the array and display it in a display value module

**Comment by targos** [comment]
I think it makes more sense to add `length` to the jpath selection. Would that be enough for you ?

**Comment by lpatiny** [comment]
The advantage of type renderer (it does not slow down everything ...) is that it would allow to display the number of elements in a linked array directly in a slick grid which is actually something I would like to do.

**Comment by targos** [comment]
you can do the same with jpath (or I don't understand the request)
