### ISSUE TITLE
mol2d type renderer and hydrogens

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#977]
The current type renderer for mol2d goes through oclCode.

https://github.com/NPellet/visualizer/blob/master/src/src/util/typerenderer.js#L274

The problem is that those code skips all the hydrogens which may be quite annoying in some cases. I htink that for mol2d we should stay with molfile and create the molecule OCL object from it.

**Comment by targos** [comment]
We are now using SVG by default and hydrogens are kept
