### ISSUE TITLE
CouchAttachments has no access to attachments if not public

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#978]
I don't know how to send credential so that couch attachments can load attachment of a non public view

**Comment by stropitek** [comment]
I always send credentials, it should work on private views

**Comment by lpatiny** [comment]
You are right. In fact it is when I load the image using image-js. I just used the URL so I don't know what should I do.

**Comment by stropitek** [comment]
With couchdb attachment you can get the data content as a Blob by doing 
```js
cdb.get(attachmentName, {responseType: 'blob'})
```

You can then convert the Blob to a dataUrl before passing it to image-js
```js
function blobToDataURL(blob, callback) {
    var a = new FileReader();
    a.onload = function(e) {callback(e.target.result);}
    a.readAsDataURL(blob);
}
```

**Comment by lpatiny** [comment]
Not an easy solution ... how we could forward credential ? Can it be in the url somehow ?

**Comment by targos** [comment]
You have two options:
- Download the image data as an ArrayBuffer (`{responseType: 'arraybuffer'}`) and then pass it to Image.load
- Add `{withCredentials: true}` to the Image.load options

**Comment by stropitek** [comment]
Ok, didn't know `withCredentials` was an option in image-js

**Comment by lpatiny** [comment]
It is not (yet)
