### ISSUE TITLE
Same kind of api for UI.progress ?

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#983]
API.loading is a function that accepts id and message and can be stopped using 'stopLoading'

https://github.com/NPellet/visualizer/blob/master/src/src/util/api.js#L220

I would do the same for 'progress'

UI.progress(id, message) (message being optionnal and id becomes the message in that case)
UI.stopProgress(id)

**Comment by stropitek** [comment]
There is already
```js
var id = UI.startProgress(message);
UI.stopProgress(id);
```

I shows a notification bar indicating something is in progress. Not sure if this is what you are looking for

**Comment by lpatiny** [comment]
I know I just was thinking it should be the same kind of parameters and logic as API.loading
