### ISSUE TITLE
SVG ocl problem

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#985]
In the view

https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F5dc37671c90094f5255872aa989706e2%2Fview.json

Just click on Demo and scroll a little bit some molecules will not have bonds

![image](https://cloud.githubusercontent.com/assets/1484241/19938642/f89dd724-a125-11e6-9950-0ca3d19ddc30.png)

Actually the bonds are in the SVG but the width of them is 0. I don't know if this bug is from OCL or from the visualizer.

**Comment by targos** [comment]
@rufenerc

**Comment by lpatiny** [comment]
Here is a public view for the test

http://www.cheminfo.org/Chemistry/Parsing_data/SDF_as_a_table/index.html?v=2.71.3

Just click on 'Demo' and scroll a little bit down.

**Comment by rufenerc** [comment]
Fixed

**Comment by targos** [comment]
updated openchemlib
