### ISSUE TITLE
Periodic table problem

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#986]
The layout is still a little bit strange. A cell takes too much vertical space.

https://my.cheminfo.org/?viewURL=https%3A%2F%2Fmydb.cheminfo.org%2Fdb%2Fvisualizer%2Fentry%2F3e54b136946b03d66fc7e7e64b63d694%2Fview.json

**Comment by stropitek** [comment]
Cannot reproduce in Chrome. Did you have this issue in Safari?

**Comment by lpatiny** [comment]
Just try on my mac the link and I have scrollbars that appear the second time. (there is a quick blink when you load the page, would be nice BTW if we can remove it ?)

![image](https://cloud.githubusercontent.com/assets/1484241/20679781/a1a7d4e8-b59c-11e6-95c0-7bcd8288eaa2.png)

**Comment by stropitek** [comment]
Can you retry? I recently made a fix that my fix that
