### ISSUE TITLE
Spreadsheet library

### ISSUE THREAD

**Issue by targos** [NPellet/visualizer#991]
https://github.com/Spreadsheets/WickedGrid

**Comment by targos** [comment]
@lpatiny could you test it?

**Comment by lpatiny** [comment]
It is probably the best javascript spreadsheet that is available in open-source but currently unfortunately not usable ... I will fill some tickets in the project and we will see

**Comment by lpatiny** [comment]
I could also not let run the examples locally (they don't work on the website) but maybe it is trivial changes. 

In the examples they call
```	<script src="../bower_components/jquery-legacy/dist/jquery.js"></script>```

But when I do a bower install I have ```"../bower_components/jquery/dist/jquery.js```

Also in the examples the library seems not to extend jquery ($.sheet is undefined). I guess I'm doing a mistake ...
