### ISSUE TITLE
jsGraph (spectra displayer) and X axis modification

### ISSUE THREAD

**Issue by lpatiny** [NPellet/visualizer#997]
I could not let work the conversion of epoch to a time label. Seems the other conversions are also problematic

@NPellet 
Could be related to jsGraph itself ?
![image](https://cloud.githubusercontent.com/assets/1484241/20454610/1ea03908-ae46-11e6-82ef-829ef14a7a6a.png)

**Comment by NPellet** [comment]
Probably, but the lines are not matching. You guys didn't update to the
last version, I guess ?

2016-11-19 10:51 GMT+01:00 Luc Patiny <notifications@github.com>:

**Comment by NPellet** [comment]
Ah well anyway the time axis hasn't been migrated to ES6. It can indeed not
work like that. Should be fixed by Monday.

2016-11-19 11:39 GMT+01:00 Norman Pellet <norman.pellet@gmail.com>:

**Comment by NPellet** [comment]
Normally fixed in 1.16.5.

Let me know if you still see some issues.

**Comment by targos** [comment]
I confirm it's fixed. Thanks.
